import type { Task551ReviewableFreezeReceiptV1 } from "../../../scripts/task551DatabaseBaseline/digestContract";
import type { ScaleProfile } from "../../../tests/perf/fixtures/task551DatabaseScale";

export type Task551DatabaseFreezeReceipt = Task551ReviewableFreezeReceiptV1;

export const TASK551_DATABASE_FREEZE_RECEIPT: Readonly<
  Record<ScaleProfile, Task551DatabaseFreezeReceipt>
> = {
  small: {
    reviewState: "candidate",
    profile: "small",
    provenanceCommit: "7029fb7ee615b256e20f3ed191f54b1ac13b5c0e",
    contractDigest: "df9d79bb36a3bb9e9edd5a03fdd4ca3e255b6c4575b1b62280a068f70e8e8bfb",
    fixtureDigest: "88b987d9b5f0316fcbfded800832c47cfc4808594394857f6bdbd77a8c09a931",
    schemaDigest: "7bc101edcad4e815384c836d8ab3c4217081b662d2e5fd6b70b73f2e521b5c49",
    runnerDigest: "34610ac32c8213abf48d49aa6baa0bee44d6109f168c120996513976e15343bc",
    platform: "linux",
    arch: "aarch64",
    cpuModel: "sanitized",
    logicalCpus: 1,
    memoryMb: 1,
    postgresMajor: 1,
    postgresConfigDigest: "sanitized-postgres-config",
    bunVersion: "bun",
    poolCapacity: 2,
    containerMode: "unknown",
    scopeDigest: "sanitized-scope",
    calibration: {
      warmups: 20,
      samples: 100,
      medianMs: 1,
    },
    statementCeilings: [
      {
        statementId: "admin-pages-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 500,
          rowsReturnedMax: 101,
          transferredBytesMax: 17002,
          sharedBuffersMax: 1,
          p50MsMax: 80.9,
          p95MsMax: 108.1,
          p99MsMax: 130.7,
        },
      },
      {
        statementId: "admin-pages-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 500,
          rowsReturnedMax: 1,
          transferredBytesMax: 134,
          sharedBuffersMax: 1,
          p50MsMax: 174.2,
          p95MsMax: 238,
          p99MsMax: 240.3,
        },
      },
      {
        statementId: "admin-pages-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 5,
          rowsReturnedMax: 51,
          transferredBytesMax: 126,
          sharedBuffersMax: 1,
          p50MsMax: 154.9,
          p95MsMax: 200.8,
          p99MsMax: 223.8,
        },
      },
      {
        statementId: "admin-entries-global-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 101,
          transferredBytesMax: 3508,
          sharedBuffersMax: 1,
          p50MsMax: 151.3,
          p95MsMax: 184.1,
          p99MsMax: 255.9,
        },
      },
      {
        statementId: "admin-entries-global-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 2000,
          rowsReturnedMax: 1,
          transferredBytesMax: 138,
          sharedBuffersMax: 1,
          p50MsMax: 148.2,
          p95MsMax: 187.1,
          p99MsMax: 230.2,
        },
      },
      {
        statementId: "admin-entries-global-facets",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 21,
          rowsReturnedMax: 102,
          transferredBytesMax: 1367,
          sharedBuffersMax: 1,
          p50MsMax: 148.7,
          p95MsMax: 175.2,
          p99MsMax: 185,
        },
      },
      {
        statementId: "admin-entries-typed-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100,
          rowsReturnedMax: 101,
          transferredBytesMax: 258,
          sharedBuffersMax: 1,
          p50MsMax: 154.9,
          p95MsMax: 213.1,
          p99MsMax: 249.3,
        },
      },
      {
        statementId: "admin-entries-typed-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 2000,
          rowsReturnedMax: 1,
          transferredBytesMax: 138,
          sharedBuffersMax: 1,
          p50MsMax: 152.1,
          p95MsMax: 169.1,
          p99MsMax: 188.6,
        },
      },
      {
        statementId: "admin-entries-typed-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 51,
          transferredBytesMax: 127,
          sharedBuffersMax: 1,
          p50MsMax: 146.6,
          p95MsMax: 176.4,
          p99MsMax: 204,
        },
      },
      {
        statementId: "admin-posts-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 101,
          transferredBytesMax: 1778,
          sharedBuffersMax: 1,
          p50MsMax: 147.5,
          p95MsMax: 163.3,
          p99MsMax: 163.9,
        },
      },
      {
        statementId: "admin-posts-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 1000,
          rowsReturnedMax: 1,
          transferredBytesMax: 137,
          sharedBuffersMax: 1,
          p50MsMax: 147.3,
          p95MsMax: 203.2,
          p99MsMax: 254,
        },
      },
      {
        statementId: "admin-posts-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 51,
          transferredBytesMax: 127,
          sharedBuffersMax: 1,
          p50MsMax: 184.1,
          p95MsMax: 287.8,
          p99MsMax: 404.2,
        },
      },
      {
        statementId: "admin-users-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 80,
          rowsReturnedMax: 101,
          transferredBytesMax: 4334,
          sharedBuffersMax: 1,
          p50MsMax: 186.3,
          p95MsMax: 370.3,
          p99MsMax: 493.1,
        },
      },
      {
        statementId: "admin-users-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100,
          rowsReturnedMax: 1,
          transferredBytesMax: 116,
          sharedBuffersMax: 1,
          p50MsMax: 155,
          p95MsMax: 221.2,
          p99MsMax: 266.4,
        },
      },
      {
        statementId: "admin-users-roles-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 80,
          rowsReturnedMax: 51,
          transferredBytesMax: 127,
          sharedBuffersMax: 1,
          p50MsMax: 148.9,
          p95MsMax: 174.6,
          p99MsMax: 248,
        },
      },
      {
        statementId: "admin-forms-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 21,
          rowsReturnedMax: 101,
          transferredBytesMax: 3566,
          sharedBuffersMax: 1,
          p50MsMax: 74.5,
          p95MsMax: 97.3,
          p99MsMax: 97.5,
        },
      },
      {
        statementId: "admin-forms-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 21,
          rowsReturnedMax: 1,
          transferredBytesMax: 114,
          sharedBuffersMax: 1,
          p50MsMax: 147.4,
          p95MsMax: 174.7,
          p99MsMax: 238.3,
        },
      },
      {
        statementId: "admin-form-submissions-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 170,
          rowsReturnedMax: 101,
          transferredBytesMax: 15237,
          sharedBuffersMax: 1,
          p50MsMax: 76.7,
          p95MsMax: 81.5,
          p99MsMax: 84.6,
        },
      },
      {
        statementId: "admin-form-submissions-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 2001,
          rowsReturnedMax: 1,
          transferredBytesMax: 116,
          sharedBuffersMax: 1,
          p50MsMax: 149.2,
          p95MsMax: 163.7,
          p99MsMax: 259.1,
        },
      },
      {
        statementId: "admin-media-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 101,
          transferredBytesMax: 3252,
          sharedBuffersMax: 1,
          p50MsMax: 149.9,
          p95MsMax: 202.2,
          p99MsMax: 234.4,
        },
      },
      {
        statementId: "admin-media-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 2000,
          rowsReturnedMax: 1,
          transferredBytesMax: 102,
          sharedBuffersMax: 1,
          p50MsMax: 146.3,
          p95MsMax: 155.5,
          p99MsMax: 173.5,
        },
      },
      {
        statementId: "admin-media-facets",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 102,
          transferredBytesMax: 137,
          sharedBuffersMax: 1,
          p50MsMax: 147.5,
          p95MsMax: 158.8,
          p99MsMax: 163,
        },
      },
      {
        statementId: "admin-booking-reservations-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 109,
          rowsReturnedMax: 101,
          transferredBytesMax: 21274,
          sharedBuffersMax: 1,
          p50MsMax: 149.4,
          p95MsMax: 162.4,
          p99MsMax: 182.4,
        },
      },
      {
        statementId: "admin-booking-reservations-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 2000,
          rowsReturnedMax: 1,
          transferredBytesMax: 154,
          sharedBuffersMax: 1,
          p50MsMax: 146.1,
          p95MsMax: 178.4,
          p99MsMax: 243.6,
        },
      },
      {
        statementId: "admin-booking-resources-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 101,
          transferredBytesMax: 3444,
          sharedBuffersMax: 1,
          p50MsMax: 73.8,
          p95MsMax: 80.2,
          p99MsMax: 90.2,
        },
      },
      {
        statementId: "admin-booking-resources-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 1,
          transferredBytesMax: 88,
          sharedBuffersMax: 1,
          p50MsMax: 145.3,
          p95MsMax: 154.6,
          p99MsMax: 168.5,
        },
      },
      {
        statementId: "admin-booking-services-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 101,
          transferredBytesMax: 3404,
          sharedBuffersMax: 1,
          p50MsMax: 73.2,
          p95MsMax: 78.5,
          p99MsMax: 83.9,
        },
      },
      {
        statementId: "admin-booking-services-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 20,
          rowsReturnedMax: 1,
          transferredBytesMax: 88,
          sharedBuffersMax: 1,
          p50MsMax: 145.8,
          p95MsMax: 154.5,
          p99MsMax: 155.2,
        },
      },
      {
        statementId: "admin-booking-blackouts-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 111,
          rowsReturnedMax: 101,
          transferredBytesMax: 17298,
          sharedBuffersMax: 1,
          p50MsMax: 76.8,
          p95MsMax: 88,
          p99MsMax: 91.8,
        },
      },
      {
        statementId: "admin-booking-blackouts-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 500,
          rowsReturnedMax: 1,
          transferredBytesMax: 77,
          sharedBuffersMax: 1,
          p50MsMax: 72.4,
          p95MsMax: 126.2,
          p99MsMax: 165,
        },
      },
      {
        statementId: "admin-booking-service-resources-fixed-list",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100,
          rowsReturnedMax: 101,
          transferredBytesMax: 12564,
          sharedBuffersMax: 1,
          p50MsMax: 76.2,
          p95MsMax: 86,
          p99MsMax: 88.7,
        },
      },
      {
        statementId: "admin-booking-schedules-fixed-list",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 140,
          rowsReturnedMax: 101,
          transferredBytesMax: 15134,
          sharedBuffersMax: 1,
          p50MsMax: 77.8,
          p95MsMax: 116.5,
          p99MsMax: 174.2,
        },
      },
    ],
    poolWaitCeiling: {
      queryCountMax: 1,
      rowsReadMax: 1,
      rowsReturnedMax: 1,
      transferredBytesMax: 64,
      sharedBuffersMax: 4,
      p50MsMax: 106.8,
      p95MsMax: 148.5,
      p99MsMax: 178.6,
    },
    reviewableReceiptDigest: "f29a07ae13aeaea0cf34a10ce021067a8711f94dca46c609750f554550b51a0e",
  },
  large: {
    reviewState: "reviewed",
    profile: "large",
    provenanceCommit: "7029fb7ee615b256e20f3ed191f54b1ac13b5c0e",
    contractDigest: "df9d79bb36a3bb9e9edd5a03fdd4ca3e255b6c4575b1b62280a068f70e8e8bfb",
    fixtureDigest: "88b987d9b5f0316fcbfded800832c47cfc4808594394857f6bdbd77a8c09a931",
    schemaDigest: "7bc101edcad4e815384c836d8ab3c4217081b662d2e5fd6b70b73f2e521b5c49",
    runnerDigest: "34610ac32c8213abf48d49aa6baa0bee44d6109f168c120996513976e15343bc",
    platform: "linux",
    arch: "aarch64",
    cpuModel: "sanitized",
    logicalCpus: 1,
    memoryMb: 1,
    postgresMajor: 1,
    postgresConfigDigest: "sanitized-postgres-config",
    bunVersion: "bun",
    poolCapacity: 10,
    containerMode: "unknown",
    scopeDigest: "sanitized-scope",
    calibration: {
      warmups: 20,
      samples: 100,
      medianMs: 1,
    },
    statementCeilings: [
      {
        statementId: "admin-pages-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-pages-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-pages-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 51,
          transferredBytesMax: 1224,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-global-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-global-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-global-facets",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 102,
          transferredBytesMax: 2448,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-typed-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-typed-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-entries-typed-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 51,
          transferredBytesMax: 1224,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-posts-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-posts-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-posts-authors-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10,
          rowsReturnedMax: 51,
          transferredBytesMax: 1224,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-users-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-users-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 10000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 64,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-users-roles-facet",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 3000,
          rowsReturnedMax: 51,
          transferredBytesMax: 1224,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-forms-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-forms-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 200,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-form-submissions-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-form-submissions-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-media-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-media-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-media-facets",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 1000,
          rowsReturnedMax: 102,
          transferredBytesMax: 2448,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-reservations-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 50000,
          rowsReturnedMax: 101,
          transferredBytesMax: 65536,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-reservations-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-resources-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-resources-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 1000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 16,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-services-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-services-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 1000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 16,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-blackouts-page",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-blackouts-fixed-summary",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 100000,
          rowsReturnedMax: 1,
          transferredBytesMax: 1024,
          sharedBuffersMax: 256,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-service-resources-fixed-list",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
      {
        statementId: "admin-booking-schedules-fixed-list",
        ceiling: {
          queryCountMax: 1,
          rowsReadMax: 101,
          rowsReturnedMax: 101,
          transferredBytesMax: 6464,
          sharedBuffersMax: 8,
          p50MsMax: 5,
          p95MsMax: 10,
          p99MsMax: 20,
        },
      },
    ],
    poolWaitCeiling: {
      queryCountMax: 1,
      rowsReadMax: 1,
      rowsReturnedMax: 1,
      transferredBytesMax: 64,
      sharedBuffersMax: 4,
      p50MsMax: 5,
      p95MsMax: 10,
      p99MsMax: 20,
    },
    reviewableReceiptDigest: "2a0ab152f60caf10eca261f64a90d7ec0de51ac24dcb0840229047c7e569fe78",
  },
} as const;
