// Canonical raw action rows for the TASK-540 button-image flow.
// The composition root deep-freezes and validates the complete ordered manifest.
export const BUTTON_IMAGE_ACTION_ROWS = [
  [
    "bi-001-light-proof",
    "p1/0",
    "observe(theme-light)",
    "cold builder -> `aria-pressed=false` + computed colors -> light proven",
    "set-045 / absent -> absent",
  ],
  [
    "bi-002-resize",
    "p1/0",
    "resize(1280,900)",
    "light builder -> viewport -> 1280x900",
    "bi-001 / absent -> absent",
  ],
  [
    "bi-003-button-before",
    "p1/0",
    "blocksBefore(palette.button)",
    "canvas visible -> exact block-ID set + Insert selected -> Button baseline captured",
    "bi-002 / absent -> absent",
  ],
  [
    "bi-004-button-click",
    "p1/0",
    'click(S.palette("Button"))',
    "Button baseline -> click receipt -> one Button inserted/selected",
    "bi-003 / absent -> absent",
  ],
  [
    "bi-005-button-capture",
    "p1/0",
    'captureNew(palette.button,"button",bi-003)',
    "insertion settled -> one new ID -> `palette.button` frozen",
    "bi-003,bi-004 / absent -> absent",
  ],
  [
    "bi-006-bound-open-primary",
    "p1/0",
    "click(S.boundField)",
    "Button selected -> menu visible -> bound-field menu open",
    "bi-005 / absent -> absent",
  ],
  [
    "bi-007-bound-primary",
    "p1/0",
    'click(S.fieldOption("Primary Url","text"))',
    "menu open -> visible Primary Url option -> semantic `primaryUrl` field bound",
    "bi-006 / absent -> absent",
  ],
  [
    "bi-008-bound-open-secondary",
    "p1/0",
    "click(S.boundField)",
    "Primary bound -> menu visible -> menu open",
    "bi-007 / absent -> absent",
  ],
  [
    "bi-009-bound-secondary",
    "p1/0",
    'click(S.fieldOption("Secondary Url","text"))',
    "menu open -> selected label -> Secondary URL bound",
    "bi-008 / absent -> absent",
  ],
  [
    "bi-010-use-static",
    "p1/0",
    "click(S.staticLink)",
    "Secondary bound -> inspector transition -> binding removed/static input visible",
    "bi-009 / absent -> absent",
  ],
  [
    "bi-011-fill-static",
    "p1/0",
    "fill(S.staticLinkInput,paths.nestedHash)",
    "static input visible -> value -> static link authored",
    "bi-010 / absent -> absent",
  ],
  [
    "bi-012-bound-open-final",
    "p1/0",
    "click(S.boundField)",
    "static link authored -> menu visible -> menu open",
    "bi-011 / absent -> absent",
  ],
  [
    "bi-013-bound-final",
    "p1/0",
    'click(S.fieldOption("Primary Url","text"))',
    "menu open -> visible Primary Url option -> exactly semantic `primaryUrl` field bound",
    "bi-012 / absent -> absent",
  ],
  [
    "bi-014-builder-save",
    "p1/0",
    "click(S.builderSave)",
    "dirty builder -> save settlement -> builder clean",
    "bi-013 / absent -> absent",
  ],
  [
    "bi-015-persisted-binding",
    "p1/0",
    "observe(binding-after-save)",
    "save settled -> strict persisted read -> post-Save binding sample frozen",
    "bi-014 / absent -> absent",
  ],
  [
    "bi-016-list",
    "p1/0",
    "goto(paths.screens)",
    "builder clean -> URL -> Screen list",
    "bi-015 / absent -> absent",
  ],
  [
    "bi-016a-auth-rate-window-barrier",
    "p1/0",
    "authRateWindowBarrier()",
    'Screen list stable/bounded rate epoch -> configured auth window naturally expires when enabled or timer is skipped when disabled + bounded realm-stability proof -> exact `{"barrierSatisfied":true}`',
    "bi-016 / absent -> absent",
  ],
  [
    "bi-017-reopen",
    "p1/0",
    "goto(paths.builder)",
    "Screen list -> URL/canvas marker -> saved builder reopened",
    "bi-016a-auth-rate-window-barrier / absent -> absent",
  ],
  [
    "bi-018-reopen-proof",
    "p1/0",
    "assert(persisted-no-empty-binding)",
    "reopened -> strict observation -> binding still exact",
    "bi-017 / absent -> absent",
  ],
  [
    "bi-019-cache-cold",
    "p1/0",
    "assert(media-cache-cold-before-route)",
    "no prior entry/media consumer -> exact aggregate count -> media GET count 0",
    "bi-018 / absent -> absent",
  ],
  [
    "bi-020-media-route-setup",
    "p1/0",
    "route(media-prior-resolution,route-setup)",
    "cache cold -> registered task-owned media tuple -> delayed isolating route installed",
    "bi-019 / absent -> installed",
  ],
  [
    "bi-021-records-link",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "delayed route installed/builder -> URL + exact visible Record actions control -> records workspace ready",
    "bi-020 / installed -> installed",
  ],
  [
    "bi-022-entry-link",
    "p1/0",
    "click(S.recordActions,S.editRecord)",
    "records workspace ready -> open exact Record actions menu then click exact Edit record item -> entry navigation started",
    "bi-021 / installed -> installed",
  ],
  [
    "bi-023-media-route-hit",
    "p1/0",
    "route(media-prior-resolution,route-hit-read)",
    "entry mounting -> backing list validated + exact acquired fixture projected -> route hit exactly 1/pending",
    "bi-022 / installed -> hit",
  ],
  [
    "bi-024-prior-resolution",
    "p1/0",
    "assert(prior-media-resolution-pending)",
    "hit pending -> selected target + pending source -> prior protected value visible",
    "bi-023 / hit -> hit",
  ],
  [
    "bi-025-select-race-image",
    "p1/0",
    "click(S.selectBlock(screen.blockIds.raceImage))",
    "entry visible -> selection state -> race Image selected",
    "bi-024 / hit -> hit",
  ],
  [
    "bi-026-clear-presentation",
    "p1/0",
    "click(S.presentationClear)",
    "direct override selected -> dirty override -> newer local clear visible",
    "bi-025 / hit -> hit",
  ],
  [
    "bi-027-newer-presentation",
    "p1/0",
    "assert(newer-media-winner-selected-pending)",
    "clear applied/hit pending -> DOM source state -> missing-field placeholder wins",
    "bi-026 / hit -> hit",
  ],
  [
    "bi-028-media-pending-shot",
    "p1/0",
    "screen(media-prior-pending)",
    "newer state visible -> PNG -> pending-race screenshot created",
    "bi-027 / hit -> hit",
  ],
  [
    "bi-029-media-count-before",
    "p1/0",
    "media-count-before-release",
    "route pending -> exact count -> count 1",
    "bi-023 / hit -> hit",
  ],
  [
    "bi-030-media-release",
    "p1/0",
    "route(media-prior-resolution,route-release)",
    "validated task-owned projection held -> fulfillment receipt -> isolated response released/UI settled",
    "bi-023,bi-029 / hit -> released",
  ],
  [
    "bi-031-stale-protected",
    "p1/0",
    "assert(stale-media-result-ignored)",
    "released/settled -> DOM source state -> stale result cannot overwrite clear",
    "bi-026,bi-030 / released -> released",
  ],
  [
    "bi-032-media-count-after",
    "p1/0",
    "media-count-after-release",
    "settlement complete -> exact count -> still 1",
    "bi-030 / released -> released",
  ],
  [
    "bi-033-media-unroute",
    "p1/0",
    "route(media-prior-resolution,unroute)",
    "released and count proven -> `true` -> route absent",
    "bi-031,bi-032 / released -> absent",
  ],
  [
    "bi-034-browse-direct",
    "p1/0",
    "click(S.browseMedia)",
    "race Image selected + task-owned cache -> dialog -> Media library visible with exact fixture",
    "bi-033 / absent -> absent",
  ],
  [
    "bi-035-select-direct-media",
    "p1/0",
    "click(S.mediaCard(media.title))",
    "exact media card visible -> selected ID -> direct override uses acquired media",
    "bi-034 / absent -> absent",
  ],
  [
    "bi-036-direct-safe",
    "p1/0",
    "assert(direct-image-safe-url)",
    "media resolved -> DOM img/url -> acquired safe URL rendered",
    "bi-035 / absent -> absent",
  ],
  [
    "bi-037-clear-direct",
    "p1/0",
    "click(S.presentationClear)",
    "direct media visible -> override clear -> missing binding restored",
    "bi-036 / absent -> absent",
  ],
  [
    "bi-038-direct-missing",
    "p1/0",
    "assert(missing-or-unsafe-placeholder)",
    "clear settled -> placeholder/URL state -> no unsafe image emitted",
    "bi-037 / absent -> absent",
  ],
  [
    "bi-039-select-media-field",
    "p1/0",
    "click(S.selectBlock(screen.blockIds.mediaField))",
    "entry visible -> selected state -> preseed Media field selected",
    "bi-038 / absent -> absent",
  ],
  [
    "bi-040-browse-field",
    "p1/0",
    "click(S.browseMedia)",
    "Media field selected + task-owned cache -> dialog -> Media library visible with exact fixture",
    "bi-039 / absent -> absent",
  ],
  [
    "bi-041-select-field-media",
    "p1/0",
    "click(S.mediaCard(media.title))",
    "exact media card visible -> selected ID -> UUID draft selected",
    "bi-040 / absent -> absent",
  ],
  [
    "bi-042-save-presentation",
    "p1/0",
    "click(S.presentationSave)",
    "presentation dirty -> exact PATCH success + `Saving...` absent + clean-disabled Save presentation control -> override clean",
    "bi-041 / absent -> absent",
  ],
  [
    "bi-043-media-uuid",
    "p1/0",
    "assert(media-field-keeps-uuid)",
    "save settled -> unique visible fixture display title + canonical rendered image source mapped to the captured media fixture, plus authenticated persisted read -> captured UUID retained/no resolved URL persisted",
    "bi-042 / absent -> absent",
  ],
  [
    "bi-044-builder-return",
    "p1/0",
    "goto(paths.builder)",
    "entry clean -> URL/canvas -> builder visible",
    "bi-043 / absent -> absent",
  ],
  [
    "bi-045-image-before",
    "p1/0",
    "blocksBefore(palette.image)",
    "canvas visible -> ID set + Insert selected -> Image baseline captured",
    "bi-044 / absent -> absent",
  ],
  [
    "bi-046-image-click",
    "p1/0",
    'click(S.palette("Image"))',
    "baseline -> click -> one Image inserted",
    "bi-045 / absent -> absent",
  ],
  [
    "bi-047-image-capture",
    "p1/0",
    'captureNew(palette.image,"image",bi-045)',
    "insertion settled -> one new ID -> palette Image frozen",
    "bi-045,bi-046 / absent -> absent",
  ],
  [
    "bi-048-image-bound-open",
    "p1/0",
    "click(S.boundField)",
    "Image selected -> menu -> menu open",
    "bi-047 / absent -> absent",
  ],
  [
    "bi-049-image-bound-media",
    "p1/0",
    'click(S.fieldOption("Media Asset","media"))',
    "menu open -> exact option -> palette Image media-bound",
    "bi-048 / absent -> absent",
  ],
  [
    "bi-050-field-before",
    "p1/0",
    "blocksBefore(palette.mediaField)",
    "canvas visible -> ID set + Insert selected -> Field baseline captured",
    "bi-049 / absent -> absent",
  ],
  [
    "bi-051-field-click",
    "p1/0",
    'click(S.palette("Field"))',
    "baseline/Insert palette remains visible -> click -> one Field inserted",
    "bi-050 / absent -> absent",
  ],
  [
    "bi-052-field-capture",
    "p1/0",
    'captureNew(palette.mediaField,"field",bi-050)',
    "insertion settled -> one new ID -> palette Field frozen",
    "bi-050,bi-051 / absent -> absent",
  ],
  [
    "bi-053-field-bound-open",
    "p1/0",
    "click(S.boundField)",
    "Field selected -> menu -> menu open",
    "bi-052 / absent -> absent",
  ],
  [
    "bi-054-field-bound-media",
    "p1/0",
    'click(S.fieldOption("Media Asset","media"))',
    "menu open -> exact option -> palette Field media-bound",
    "bi-053 / absent -> absent",
  ],
  [
    "bi-055-save-palette-media",
    "p1/0",
    "click(S.builderSave)",
    "palette media blocks dirty -> save settlement -> builder clean",
    "bi-054 / absent -> absent",
  ],
  [
    "bi-056-entry-return",
    "p1/0",
    "goto(paths.entry)",
    "builder clean -> URL/document marker -> entry visible",
    "bi-055 / absent -> absent",
  ],
  [
    "bi-056a-safe-link-observe",
    "p1/0",
    "observe(safe-link-anchor-before-activation)",
    "entry visible -> tag/href/rect -> safe anchor sample frozen",
    "bi-056 / absent -> absent",
  ],
  [
    "bi-057-safe-link-click",
    "p1/0",
    "click(S.buttonAffordance(palette.button))",
    "safe anchor present -> navigation -> front hash destination reached",
    "bi-056a-safe-link-observe / absent -> absent",
  ],
  [
    "bi-058-safe-link-proof",
    "p1/0",
    "assert(safe-link-front-url)",
    "front loaded + anchor sample -> href/page URL -> exact safe front URL",
    "bi-056a-safe-link-observe,bi-057 / absent -> absent",
  ],
  [
    "bi-059-entry-after-front",
    "p1/0",
    "goto(paths.entry)",
    "front assertion complete -> URL -> entry visible",
    "bi-058 / absent -> absent",
  ],
  [
    "bi-060-unsafe-patch",
    "runtime",
    "api(patch-screen-button-binding-secondary-url)",
    "entry baseline already holds unsafe Secondary URL -> one Screen PATCH -> Button rebound",
    "bi-059 / absent -> absent",
  ],
  [
    "bi-061-unsafe-proof-read",
    "runtime",
    "apiRead(screen-button-binding-secondary-url)",
    "PATCH settled -> exact binding + baseline entry capture -> unsafe fixture proven",
    "bi-060 / absent -> absent",
  ],
  [
    "bi-061a-auth-rate-window-barrier",
    "p1/0",
    "authRateWindowBarrier()",
    'unsafe fixture proven/bounded rate epoch -> configured auth window naturally expires when enabled or timer is skipped when disabled + bounded realm-stability proof -> exact `{"barrierSatisfied":true}`',
    "bi-061 / absent -> absent",
  ],
  [
    "bi-062-entry-unsafe-reload",
    "p1/0",
    "goto(paths.entry)",
    "unsafe fixture proven -> URL/document -> entry rerendered",
    "bi-061a-auth-rate-window-barrier / absent -> absent",
  ],
  [
    "bi-063-unsafe-disabled",
    "p1/0",
    "assert(unsafe-link-disabled)",
    "entry rerendered -> span/ARIA/anchor count -> unsafe URL inert",
    "bi-062 / absent -> absent",
  ],
  [
    "bi-064-baseline-restore",
    "runtime",
    "api(reset-screen-baseline)",
    "unsafe assertion complete -> one Screen PATCH -> baseline restored",
    "bi-063 / absent -> absent",
  ],
  [
    "bi-065-baseline-proof",
    "runtime",
    "apiRead(screen-baseline)",
    "restore settled -> exact baseline document -> reset proven",
    "bi-064 / absent -> absent",
  ],
  [
    "bi-066-final-entry",
    "p1/0",
    "goto(paths.entry)",
    "reset proven -> URL/document -> final entry visible",
    "bi-065 / absent -> absent",
  ],
  [
    "bi-067-final-shot",
    "p1/0",
    "screen(button-image-light)",
    "final safe state -> PNG -> flow screenshot created",
    "bi-066 / absent -> absent",
  ],
  [
    "bi-068-log-agg-errors",
    "p1/0",
    "logs(aggregate,console-errors)",
    "flow complete -> `[]` -> aggregate errors clean",
    "bi-067 / absent -> absent",
  ],
  [
    "bi-069-log-pages-errors",
    "p1/0",
    "logs(per-page,console-errors)",
    "logger stable -> every page `[]` -> page errors clean",
    "bi-068 / absent -> absent",
  ],
  [
    "bi-070-log-agg-warnings",
    "p1/0",
    "logs(aggregate,console-warnings)",
    "flow complete -> `[]` -> aggregate warnings clean",
    "bi-069 / absent -> absent",
  ],
  [
    "bi-071-log-pages-warnings",
    "p1/0",
    "logs(per-page,console-warnings)",
    "logger stable -> every page `[]` -> page warnings clean",
    "bi-070 / absent -> absent",
  ],
  [
    "bi-072-log-agg-page-errors",
    "p1/0",
    "logs(aggregate,page-errors)",
    "flow complete -> `[]` -> aggregate page errors clean",
    "bi-071 / absent -> absent",
  ],
  [
    "bi-073-log-pages-page-errors",
    "p1/0",
    "logs(per-page,page-errors)",
    "logger stable -> every page `[]` -> flow 1 clean",
    "bi-072 / absent -> absent",
  ]
];
