// Canonical raw action rows for the TASK-540 dirty-guard flow.
// The composition root deep-freezes and validates the complete ordered manifest.
export const DIRTY_GUARD_ACTION_ROWS = [
  [
    "dg-001-entry-reset",
    "runtime",
    "api(reset-entry-baseline)",
    "flow 4 logs clean with browser draft dirty -> one PATCH -> backend entry baseline restored and browser draft remains dirty",
    "ss-035 / absent -> absent",
  ],
  [
    "dg-002-entry-proof",
    "runtime",
    "apiRead(entry-baseline)",
    "backend PATCH settled with browser draft dirty -> exact values -> backend entry reset proven and browser draft remains dirty",
    "dg-001 / absent -> absent",
  ],
  [
    "dg-003-builder",
    "p1/0",
    "goto(paths.builder)",
    "backend reset proven with browser draft dirty -> exactly one accepted beforeunload plus exact URL/canvas -> builder visible and Playwright dialog listener restored",
    "dg-002 / absent -> absent",
  ],
  [
    "dg-004-light-toggle",
    "p1/0",
    "click(S.colorMode)",
    "flow 4 dark -> aria state -> light selected",
    "dg-003 / absent -> absent",
  ],
  [
    "dg-005-light-proof",
    "p1/0",
    "observe(theme-light)",
    "toggle settled -> colors/aria -> light proven",
    "dg-004 / absent -> absent",
  ],
  [
    "dg-006-resize",
    "p1/0",
    "resize(1280,900)",
    "light builder -> viewport -> 1280x900",
    "dg-005 / absent -> absent",
  ],
  [
    "dg-007-dirty-before",
    "p1/0",
    "blocksBefore(palette.dirtyText)",
    "canvas visible -> ID set + Insert selected -> dirty Text baseline",
    "dg-006 / absent -> absent",
  ],
  [
    "dg-008-dirty-click",
    "p1/0",
    'click(S.palette("Text"))',
    "baseline -> click -> Text inserted",
    "dg-007 / absent -> absent",
  ],
  [
    "dg-009-dirty-capture",
    "p1/0",
    'captureNew(palette.dirtyText,"text",dg-007)',
    "insertion settled -> one ID -> dirty Text frozen",
    "dg-007,dg-008 / absent -> absent",
  ],
  [
    "dg-010-dirty-fill",
    "p1/0",
    "fill(S.paragraph,entry.contentDraft)",
    "Text selected -> value -> builder dirty draft authored",
    "dg-009 / absent -> absent",
  ],
  [
    "dg-011-builder-before-cancel",
    "p1/0",
    "observe(builder-draft-url-before-cancel)",
    "builder dirty -> document bytes/URL -> before sample frozen",
    "dg-010 / absent -> absent",
  ],
  [
    "dg-012-builder-nav-cancel",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "dirty builder -> dialog -> navigation suspended",
    "dg-011 / absent -> absent",
  ],
  [
    "dg-013-builder-keep",
    "p1/0",
    "click(S.keepEditing)",
    "dialog visible -> close -> builder retained",
    "dg-012 / absent -> absent",
  ],
  [
    "dg-014-builder-cancel-proof",
    "p1/0",
    "assert(builder-cancel-byte-identical)",
    "dialog canceled -> draft/URL read -> byte-identical",
    "dg-011,dg-013 / absent -> absent",
  ],
  [
    "dg-015-builder-nav-confirm",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "builder still dirty -> dialog -> navigation suspended again",
    "dg-014 / absent -> absent",
  ],
  [
    "dg-016-builder-discard",
    "p1/0",
    "click(S.discard)",
    "dialog visible -> navigation -> records workspace",
    "dg-015 / absent -> absent",
  ],
  [
    "dg-017-builder-confirm-proof",
    "p1/0",
    "assert(builder-confirm-navigates-once)",
    "records loaded -> URL/count/draft + exact visible Record actions control -> one navigation/discard and records workspace ready",
    "dg-011,dg-016 / absent -> absent",
  ],
  [
    "dg-018-entry-link",
    "p1/0",
    "click(S.recordActions,S.editRecord)",
    "records workspace with exact visible Record actions control -> open exact menu then click exact Edit record item -> entry visible",
    "dg-017 / absent -> absent",
  ],
  [
    "dg-019-select-headline",
    "p1/0",
    "click(S.selectBlock(screen.blockIds.headlineField))",
    "entry visible -> selection -> Headline selected",
    "dg-018 / absent -> absent",
  ],
  [
    "dg-020-headline-fill",
    "p1/0",
    'fill(S.contentEditable(screen.blockIds.headlineField,"Headline"),entry.contentDraft)',
    "headline selected -> value -> content dirty",
    "dg-019 / absent -> absent",
  ],
  [
    "dg-021-tone-open",
    "p1/0",
    "click(S.toneTrigger)",
    "selected target supports tone -> exact selected target and baseline color -> one visible positive-geometry tone menu linked by aria-controls with one visible Muted option",
    "dg-020 / absent -> absent",
  ],
  [
    "dg-022-tone-muted",
    "p1/0",
    "click(S.muted)",
    "owned tone menu open -> selected value and closed menu -> content plus presentation dirty, selection retained, override marker present, and target computed color visibly changed to the muted token",
    "dg-021 / absent -> absent",
  ],
  [
    "dg-023-entry-before-cancel",
    "p1/0",
    "observe(entry-drafts-url-before-cancel)",
    "both channels dirty -> content/presentation/URL -> before sample frozen",
    "dg-022 / absent -> absent",
  ],
  [
    "dg-024-entry-nav-cancel",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "entry dirty -> dialog -> navigation suspended",
    "dg-023 / absent -> absent",
  ],
  [
    "dg-025-entry-keep",
    "p1/0",
    "click(S.keepEditing)",
    "dialog visible -> close -> entry retained",
    "dg-024 / absent -> absent",
  ],
  [
    "dg-026-entry-cancel-bytes",
    "p1/0",
    "assert(entry-cancel-byte-identical)",
    "canceled -> both drafts -> byte-identical",
    "dg-023,dg-025 / absent -> absent",
  ],
  [
    "dg-027-entry-cancel-url",
    "p1/0",
    "assert(entry-cancel-url-stable)",
    "canceled -> before/after URL -> byte-identical",
    "dg-023,dg-025 / absent -> absent",
  ],
  [
    "dg-028-save-route-setup",
    "p1/0",
    "route(entry-save-failure,route-setup)",
    "both drafts retained -> tuple -> malformed PATCH route installed",
    "dg-026,dg-027 / absent -> installed",
  ],
  [
    "dg-029-save-click",
    "p1/0",
    "click(S.entrySave)",
    "route installed/dirty -> Save -> request intercepted",
    "dg-028 / installed -> installed",
  ],
  [
    "dg-030-save-route-hit",
    "p1/0",
    "route(entry-save-failure,route-hit-read)",
    "Save pending -> captured request -> hit exactly 1",
    "dg-029 / installed -> hit",
  ],
  [
    "dg-030a-save-ui-settled",
    "p1/0",
    "observe(entry-save-failure-ui-settled)",
    "hit read -> error visible and exact Save control re-enabled -> failure settlement latch frozen",
    "dg-030 / hit -> hit",
  ],
  [
    "dg-031-error-drafts",
    "p1/0",
    "assert(entry-error-retains-both-drafts)",
    "failure UI settled -> UI/drafts/dirty flags -> content and presentation retained",
    "dg-030a-save-ui-settled / hit -> hit",
  ],
  [
    "dg-032-beforeunload",
    "p1/0",
    "assert(beforeunload-active)",
    "both channels dirty -> cancelable event -> prevented/return value set",
    "dg-031 / hit -> hit",
  ],
  [
    "dg-033-failure-shot",
    "p1/0",
    "screen(dirty-save-failure)",
    "visible error/drafts -> PNG -> failure screenshot created",
    "dg-031,dg-032 / hit -> hit",
  ],
  [
    "dg-034-save-unroute",
    "p1/0",
    "route(entry-save-failure,unroute)",
    "hit read and shot complete -> `true` -> route absent",
    "dg-030,dg-033 / hit -> absent",
  ],
  [
    "dg-035-real-retry",
    "p1/0",
    "click(S.entrySave)",
    "route absent/error visible -> real Save -> content request succeeds",
    "dg-034 / absent -> absent",
  ],
  [
    "dg-036-retry-proof",
    "p1/0",
    "assert(successful-retry-clears-persisted-channel)",
    "content Save settled -> persisted content plus the ss-006 proven empty server-presentation baseline, dg-023 local presentation bytes, and current dirty states captured -> content matches and is clean while the server presentation remains unchanged and the local presentation remains byte-identical and dirty",
    "ss-006,dg-023,dg-035 / absent -> absent",
  ],
  [
    "dg-037-entry-nav-confirm",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "presentation still dirty -> dialog -> navigation suspended",
    "dg-036 / absent -> absent",
  ],
  [
    "dg-038-entry-discard",
    "p1/0",
    "click(S.discard)",
    "dialog visible -> navigation -> records workspace",
    "dg-037 / absent -> absent",
  ],
  [
    "dg-039-entry-confirm-proof",
    "p1/0",
    "assert(entry-confirm-navigates-once)",
    "records loaded -> URL/count -> one navigation",
    "dg-038 / absent -> absent",
  ],
  [
    "dg-040-dark-toggle",
    "p1/0",
    "click(S.colorMode)",
    "final records light -> aria state -> dark selected",
    "dg-039 / absent -> absent",
  ],
  [
    "dg-041-dark-proof",
    "p1/0",
    "observe(theme-dark)",
    "toggle settled -> colors/aria -> dark proven",
    "dg-040 / absent -> absent",
  ],
  [
    "dg-042-final-shot",
    "p1/0",
    "screen(dirty-guards-final)",
    "final state -> PNG -> dirty-guards screenshot created",
    "dg-039,dg-041 / absent -> absent",
  ],
  [
    "dg-043-log-agg-errors",
    "p1/0",
    "logs(aggregate,console-errors)",
    "expected handled error excluded from console -> `[]` -> aggregate clean",
    "dg-042 / absent -> absent",
  ],
  [
    "dg-044-log-pages-errors",
    "p1/0",
    "logs(per-page,console-errors)",
    "logger stable -> every page `[]` -> pages clean",
    "dg-043 / absent -> absent",
  ],
  [
    "dg-045-log-agg-warnings",
    "p1/0",
    "logs(aggregate,console-warnings)",
    "flow complete -> `[]` -> aggregate clean",
    "dg-044 / absent -> absent",
  ],
  [
    "dg-046-log-pages-warnings",
    "p1/0",
    "logs(per-page,console-warnings)",
    "logger stable -> every page `[]` -> pages clean",
    "dg-045 / absent -> absent",
  ],
  [
    "dg-047-log-agg-page-errors",
    "p1/0",
    "logs(aggregate,page-errors)",
    "flow complete -> `[]` -> aggregate clean",
    "dg-046 / absent -> absent",
  ],
  [
    "dg-048-log-pages-page-errors",
    "p1/0",
    "logs(per-page,page-errors)",
    "logger stable -> every page `[]` -> flow 5 clean",
    "dg-047 / absent -> absent",
  ]
];
