// Canonical raw action rows for the TASK-540 recovery-cache flow.
// The composition root deep-freezes and validates the complete ordered manifest.
export const RECOVERY_CACHE_ACTION_ROWS = [
  [
    "rc-001-entry-reset",
    "runtime",
    "api(reset-entry-baseline)",
    "flow 5 clean -> one PATCH -> relation/content baseline restored",
    "dg-048 / absent -> absent",
  ],
  [
    "rc-002-entry-proof",
    "runtime",
    "apiRead(entry-baseline)",
    "PATCH settled -> exact A IDs/B empty/other values -> entry reset proven",
    "rc-001 / absent -> absent",
  ],
  [
    "rc-003-overrides-reset",
    "runtime",
    "api(reset-entry-overrides-empty)",
    "entry proven -> one contract call -> presentation overrides empty",
    "rc-002 / absent -> absent",
  ],
  [
    "rc-004-overrides-proof",
    "runtime",
    "apiRead(entry-overrides-empty)",
    "reset settled -> `[]` -> reset proven",
    "rc-003 / absent -> absent",
  ],
  [
    "rc-005-failure-route-setup",
    "p1/0",
    "route(related-first-failure,route-setup)",
    "records workspace, entry unmounted -> tuple -> malformed GET route installed",
    "rc-004 / absent -> installed",
  ],
  [
    "rc-006-entry-link",
    "p1/0",
    "goto(paths.retryEntry)",
    "route installed/records visible -> retry Screen URL/document -> retry-only entry mounting with no relation FieldRenderer",
    "rc-005 / installed -> installed",
  ],
  [
    "rc-007-failure-route-hit",
    "p1/0",
    "route(related-first-failure,route-hit-read)",
    "entry mounting -> captured request -> hit exactly 1",
    "rc-006 / installed -> hit",
  ],
  [
    "rc-008-failure-visible",
    "p1/0",
    "assert(related-error-visible-before-retry)",
    "malformed response handled -> exact related Alert/Retry plus retry-list-root scoped rows/skeleton/empty geometry -> failure visible with zero rows, exact three visible skeleton chips, no empty fallback",
    "rc-007 / hit -> hit",
  ],
  [
    "rc-009-failure-shot",
    "p1/0",
    "screen(related-first-failure)",
    "failure visible -> PNG -> first-failure screenshot created",
    "rc-008 / hit -> hit",
  ],
  [
    "rc-010-failure-unroute",
    "p1/0",
    "route(related-first-failure,unroute)",
    "hit/shot complete -> `true` -> malformed route absent",
    "rc-007,rc-009 / hit -> absent",
  ],
  [
    "rc-011-visible-retry",
    "p1/0",
    "click(S.relatedRetry)",
    "route absent/scoped related Retry visible -> real Retry -> dedicated related-failure request succeeds",
    "rc-010 / absent -> absent",
  ],
  [
    "rc-012-retry-proof",
    "p1/0",
    "assert(visible-retry-succeeds)",
    "Retry settled -> related Alert absent plus retry-list-root scoped row/skeleton/empty geometry -> exact dedicated failure-fixture row alone and visibly rendered",
    "rc-011 / absent -> absent",
  ],
  [
    "rc-012a-records-remount",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "related-list Retry succeeded/entry clean -> internal navigation + exact visible Record actions control -> records workspace ready",
    "rc-012 / absent -> absent",
  ],
  [
    "rc-012b-entry-remount",
    "p1/0",
    "click(S.recordActions,S.editRecord)",
    "records workspace ready -> open exact Record actions menu then click exact Edit record item -> fresh entry realm mounted",
    "rc-012a-records-remount / absent -> absent",
  ],
  [
    "rc-012c-picker-warm-proof",
    "p1/0",
    "observe(relation-pickers-a-b-warm)",
    "remount requests settled -> exact A1/A2/B1/B2 title buttons enabled + A related rows visible + exact positive B-list GET count frozen -> both pickers and related hook healthy/B cache warm baseline captured",
    "rc-012b-entry-remount / absent -> absent",
  ],
  [
    "rc-013-select-note",
    "p1/0",
    "click(S.selectBlock(screen.blockIds.spaceNoteField))",
    "picker warm proof complete -> selection -> unrelated text Field selected",
    "rc-012c-picker-warm-proof / absent -> absent",
  ],
  [
    "rc-014-unrelated-fill",
    "p1/0",
    'fill(S.contentEditable(screen.blockIds.spaceNoteField,"Unrelated note"),entry.relatedUnrelatedDraft)',
    "field selected -> value -> unrelated content dirty",
    "rc-013 / absent -> absent",
  ],
  [
    "rc-015-tone-open",
    "p1/0",
    "click(S.toneTrigger)",
    "selected field supports tone -> exact selected target and baseline color -> one visible positive-geometry tone menu linked by aria-controls with one visible Muted option",
    "rc-014 / absent -> absent",
  ],
  [
    "rc-016-tone-muted",
    "p1/0",
    "click(S.muted)",
    "owned tone menu open -> selected value and closed menu -> unrelated content plus presentation dirty, selection retained, override marker present, and target computed color visibly changed to the muted token",
    "rc-015 / absent -> absent",
  ],
  [
    "rc-017-unrelated-before",
    "p1/0",
    "observe(related-unrelated-drafts-before)",
    "both unrelated channels dirty -> bytes -> before sample frozen",
    "rc-016 / absent -> absent",
  ],
  [
    "rc-017a-pre-route-a-baseline",
    "p1/0",
    "observe(related-a-visible-baseline)",
    "main entry/pickers settled -> exact main-A-list-root row IDs/text/positive rects and zero skeleton/empty geometry + current p1 `navigationCount` -> pre-route visible/navigation baseline frozen",
    "rc-017 / absent -> absent",
  ],
  [
    "rc-017b-auth-rate-window-barrier",
    "p1/0",
    "authRateWindowBarrier()",
    'entry baseline stable/bounded rate epoch -> configured auth window naturally expires when enabled or timer is skipped when disabled + bounded realm-stability proof -> exact `{"barrierSatisfied":true}`',
    "rc-017a-pre-route-a-baseline / absent -> absent",
  ],
  [
    "rc-018-refresh-route-setup",
    "p1/0",
    "route(related-a-refresh,route-setup)",
    "first failure recovered/drafts and A baseline held -> tuple -> delayed A route installed",
    "rc-017b-auth-rate-window-barrier / absent -> installed",
  ],
  [
    "rc-019-related-tab-new",
    "p2/1",
    "tab-new(paths.relatedEntryA1Editor)",
    "route installed/context logger active -> identity/URL -> p2 related-A editor",
    "rc-018 / installed -> installed",
  ],
  [
    "rc-020-related-tab-edit",
    "p2/1",
    "fill(S.secondTabTitle,relatedEntries.a1.updatedTitle)",
    "p2 editor visible -> value -> harmless A1 draft",
    "rc-019 / installed -> installed",
  ],
  [
    "rc-021-related-tab-save",
    "p2/1",
    "click(S.secondTabSave)",
    "p2 dirty -> real Save draft click/request begins -> A mutation in flight",
    "rc-020 / installed -> installed",
  ],
  [
    "rc-021a-related-tab-save-settled",
    "p2/1",
    "observe(related-tab-save-settled)",
    "mutation in flight -> exact PATCH method/path/success + strict returned A1 ID/updated title + Save draft re-enabled/`Saving...` absent -> A1 persisted and cache broadcast completed",
    "rc-021 / installed -> installed",
  ],
  [
    "rc-022-related-tab-origin",
    "p1/0",
    "tab-select(0)",
    "p2 save settlement proven -> selected tab -> p1 restored",
    "rc-021a-related-tab-save-settled / installed -> installed",
  ],
  [
    "rc-023-refresh-route-hit",
    "p1/0",
    "route(related-a-refresh,route-hit-read)",
    'broadcast refresh started after p2 Save -> strict parsed authoritative updated-A response with exact A IDs/no duplicate or unknown row keys/A1 updated title -> `{"hits":1,"captured":true,"rowCount":2,"rowIdsMatch":true,"uniqueIds":true,"updatedA1Matches":true}`/pending',
    "rc-022 / installed -> hit",
  ],
  [
    "rc-024-same-target",
    "p1/0",
    "assert(same-target-visible-rows-retained)",
    "updated-A response pending -> main-A-list-root scoped row IDs/text/rects/skeleton/empty plus related Alert -> pre-route A baseline retained",
    "rc-017a-pre-route-a-baseline,rc-023 / hit -> hit",
  ],
  [
    "rc-025-clear-a1",
    "p1/0",
    "click(S.relationEntry(screen.blockIds.relationAField,relatedEntries.a1.title))",
    "relation A has A1/A2 -> toggle -> A1 cleared, A2 remains",
    "rc-024 / hit -> hit",
  ],
  [
    "rc-026-clear-a2",
    "p1/0",
    "click(S.relationEntry(screen.blockIds.relationAField,relatedEntries.a2.title))",
    "relation A has A2 -> toggle -> relation A empty",
    "rc-025 / hit -> hit",
  ],
  [
    "rc-027-target-empty",
    "p1/0",
    "assert(target-switch-immediate-empty)",
    "A empty/B untouched -> main A/B list-root scoped rows/skeleton/empty geometry -> zero rows/no empty nodes/exact three visible skeleton chips in each root",
    "rc-026 / hit -> hit",
  ],
  [
    "rc-028-select-b1",
    "p1/0",
    "click(S.relationEntry(screen.blockIds.relationBField,relatedEntries.b1.title))",
    "B picker warm/empty -> toggle -> B1 selected",
    "rc-027 / hit -> hit",
  ],
  [
    "rc-029-select-b2",
    "p1/0",
    "click(S.relationEntry(screen.blockIds.relationBField,relatedEntries.b2.title))",
    "B1 selected -> toggle -> exact B1/B2 selected",
    "rc-028 / hit -> hit",
  ],
  [
    "rc-030-only-b",
    "p1/0",
    "assert(only-b-rows-visible)",
    "B selection settled -> main-B-list-root scoped IDs/rects plus zero skeleton/empty geometry and B-list GET count unchanged from rc-012c -> exact B rows visible from warmed cache with zero network delta",
    "rc-012c-picker-warm-proof,rc-029 / hit -> hit",
  ],
  [
    "rc-031-draft-proof",
    "p1/0",
    "assert(unrelated-draft-byte-identical)",
    "B visible/A pending -> before/after bytes -> unrelated channels unchanged",
    "rc-017,rc-030 / hit -> hit",
  ],
  [
    "rc-032-diff-proof",
    "p1/0",
    "assert(relation-diff-exact)",
    "current root-scoped A/B picker pressed states + relation paths from frozen exact-reset `rc-002` baseline + exhaustive non-relation current-draft diff against frozen post-unrelated-edits `rc-017` sample -> A/B/other paths -> only A cleared+B selected and no post-`rc-017` non-relation path changed",
    "rc-002,rc-017,rc-030,rc-031 / hit -> hit",
  ],
  [
    "rc-033-stale-shot",
    "p1/0",
    "screen(related-a-stale)",
    "B visible/A pending -> PNG -> stale-A screenshot created",
    "rc-030,rc-031,rc-032 / hit -> hit",
  ],
  [
    "rc-034-refresh-release",
    "p1/0",
    "route(related-a-refresh,route-release)",
    "captured A response held -> fulfillment receipt -> response released/UI settled",
    "rc-023,rc-033 / hit -> released",
  ],
  [
    "rc-035-stale-proof",
    "p1/0",
    "assert(stale-a-cannot-commit)",
    "updated-A settled after target B -> exact main-A title and main-B row state captured -> updated A1 title absent only inside the main-A list root while B-root rows remain retained",
    "rc-034 / released -> released",
  ],
  [
    "rc-036-refresh-unroute",
    "p1/0",
    "route(related-a-refresh,unroute)",
    "stale protection proven -> `true` -> delayed route absent",
    "rc-035 / released -> absent",
  ],
  [
    "rc-037-final-shot",
    "p1/0",
    "screen(related-b-dark)",
    "B retained/dark -> PNG -> final related screenshot created",
    "rc-035,rc-036 / absent -> absent",
  ],
  [
    "rc-037a-exit-navigation",
    "p1/0",
    "click(S.recordsLink(screen.id))",
    "content/presentation/relation drafts still dirty -> real internal navigation -> discard dialog visible/navigation suspended",
    "rc-037 / absent -> absent",
  ],
  [
    "rc-037b-exit-discard",
    "p1/0",
    "click(S.discard)",
    "discard dialog visible -> real discard action -> records workspace loaded",
    "rc-037a-exit-navigation / absent -> absent",
  ],
  [
    "rc-037c-exit-proof",
    "p1/0",
    "assert(flow6-exit-discarded-once)",
    "records workspace settled -> URL/current p1 navigation count minus frozen `rc-017a` count/entry dirty badges -> exact delta one and both dirty channels unmounted",
    "rc-017a-pre-route-a-baseline,rc-037b-exit-discard / absent -> absent",
  ],
  [
    "rc-038-log-agg-errors",
    "p1/0",
    "logs(aggregate,console-errors)",
    "flow complete -> both pages aggregate `[]` -> clean",
    "rc-037c-exit-proof / absent -> absent",
  ],
  [
    "rc-039-log-pages-errors",
    "p1/0",
    "logs(per-page,console-errors)",
    "p1+p2 registered -> both `[]` -> page errors clean",
    "rc-038 / absent -> absent",
  ],
  [
    "rc-040-log-agg-warnings",
    "p1/0",
    "logs(aggregate,console-warnings)",
    "flow complete -> both pages aggregate `[]` -> clean",
    "rc-039 / absent -> absent",
  ],
  [
    "rc-041-log-pages-warnings",
    "p1/0",
    "logs(per-page,console-warnings)",
    "p1+p2 registered -> both `[]` -> page warnings clean",
    "rc-040 / absent -> absent",
  ],
  [
    "rc-042-log-agg-page-errors",
    "p1/0",
    "logs(aggregate,page-errors)",
    "flow complete -> both pages aggregate `[]` -> clean",
    "rc-041 / absent -> absent",
  ],
  [
    "rc-043-log-pages-page-errors",
    "p1/0",
    "logs(per-page,page-errors)",
    "p1+p2 registered -> both `[]` -> flow 6 clean",
    "rc-042 / absent -> absent",
  ],
  [
    "rc-044-close-second-tab",
    "p2/1",
    "tab-close(1)",
    "both-page logs captured -> close receipt -> p2 closed, identity retained in logger evidence",
    "rc-043 / absent -> absent",
  ],
  [
    "rc-045-origin-proof",
    "p1/0",
    "tab-select(0)",
    "p2 closed -> selected tab -> p1 active",
    "rc-044 / absent -> absent",
  ]
];
