// Canonical raw action rows for the TASK-540 tabs-content flow.
// The composition root deep-freezes and validates the complete ordered manifest.
export const TABS_CONTENT_ACTION_ROWS = [
  [
    "tc-001-reset",
    "runtime",
    "api(reset-entry-overrides-empty)",
    "flow 1 clean/Screen and entry already baseline -> one scoped call -> overrides empty",
    "bi-073 / absent -> absent",
  ],
  [
    "tc-002-reset-proof",
    "runtime",
    "apiRead(entry-overrides-empty)",
    "reset settled -> exact `[]` -> reset proven",
    "tc-001 / absent -> absent",
  ],
  [
    "tc-003-builder",
    "p1/0",
    "goto(paths.builder)",
    "reset proven -> URL/canvas -> builder visible",
    "tc-002 / absent -> absent",
  ],
  [
    "tc-004-dark-toggle",
    "p1/0",
    "click(S.colorMode)",
    "light proven -> aria state -> dark selected",
    "bi-001,tc-003 / absent -> absent",
  ],
  [
    "tc-005-dark-proof",
    "p1/0",
    "observe(theme-dark)",
    "toggle settled -> computed colors/aria -> dark proven",
    "tc-004 / absent -> absent",
  ],
  [
    "tc-006-resize",
    "p1/0",
    "resize(1280,900)",
    "dark builder -> viewport -> 1280x900",
    "tc-005 / absent -> absent",
  ],
  [
    "tc-007-tabs-before",
    "p1/0",
    "blocksBefore(palette.outerTabs)",
    "canvas visible -> ID set + Insert selected -> Tabs baseline captured",
    "tc-006 / absent -> absent",
  ],
  [
    "tc-008-tabs-click",
    "p1/0",
    'click(S.palette("Tabs"))',
    "baseline -> click -> one Tabs inserted",
    "tc-007 / absent -> absent",
  ],
  [
    "tc-009-tabs-capture",
    "p1/0",
    'captureNew(palette.outerTabs,"tabs",tc-007)',
    "insertion settled -> one new ID + defaults -> outer Tabs frozen",
    "tc-007,tc-008 / absent -> absent",
  ],
  [
    "tc-010-label-one",
    "p1/0",
    'fill(S.tabLabel("tab-1"),"Overview")',
    "defaults exact -> value -> tab-1 renamed",
    "tc-009 / absent -> absent",
  ],
  [
    "tc-011-label-two",
    "p1/0",
    'fill(S.tabLabel("tab-2"),"Details")',
    "tab-1 renamed -> value -> tab-2 renamed",
    "tc-010 / absent -> absent",
  ],
  [
    "tc-012-add-tab",
    "p1/0",
    "click(S.addTab)",
    "only tab-1/tab-2 -> UI mutation -> exact tab-3 added",
    "tc-011 / absent -> absent",
  ],
  [
    "tc-013-label-three",
    "p1/0",
    'fill(S.tabLabel("tab-3"),"History")',
    "tab-3 exact -> value -> tab-3 renamed",
    "tc-012 / absent -> absent",
  ],
  [
    "tc-014-edit-overview",
    "p1/0",
    'click(S.editTab("Overview"))',
    "outer selected -> active slot -> tab-1 insertion armed",
    "tc-013 / absent -> absent",
  ],
  [
    "tc-015-text-one-before",
    "p1/0",
    "blocksBefore(palette.tabOneText)",
    "tab-1 armed -> ID set + Insert selected -> Text baseline captured",
    "tc-014 / absent -> absent",
  ],
  [
    "tc-016-text-one-click",
    "p1/0",
    'click(S.palette("Text"))',
    "baseline -> click -> Text inserted in tab-1",
    "tc-015 / absent -> absent",
  ],
  [
    "tc-017-text-one-capture",
    "p1/0",
    'captureNew(palette.tabOneText,"text",tc-015)',
    "insertion settled -> one ID -> tab-1 Text frozen",
    "tc-015,tc-016 / absent -> absent",
  ],
  [
    "tc-018-text-one-fill",
    "p1/0",
    "fill(S.paragraph,tabs.text.tab-1)",
    "Text selected -> value -> Overview text authored",
    "tc-017 / absent -> absent",
  ],
  [
    "tc-019-reselect-outer-one",
    "p1/0",
    "click(S.selectBlock(palette.outerTabs))",
    "child authored -> selected state -> outer Tabs selected",
    "tc-018 / absent -> absent",
  ],
  [
    "tc-020-edit-details",
    "p1/0",
    'click(S.editTab("Details"))',
    "outer selected -> active slot -> tab-2 armed",
    "tc-019 / absent -> absent",
  ],
  [
    "tc-021-text-two-before",
    "p1/0",
    "blocksBefore(palette.tabTwoText)",
    "tab-2 armed -> ID set + Insert selected -> Text baseline captured",
    "tc-020 / absent -> absent",
  ],
  [
    "tc-022-text-two-click",
    "p1/0",
    'click(S.palette("Text"))',
    "baseline -> click -> Text inserted in tab-2",
    "tc-021 / absent -> absent",
  ],
  [
    "tc-023-text-two-capture",
    "p1/0",
    'captureNew(palette.tabTwoText,"text",tc-021)',
    "insertion settled -> one ID -> tab-2 Text frozen",
    "tc-021,tc-022 / absent -> absent",
  ],
  [
    "tc-024-text-two-fill",
    "p1/0",
    "fill(S.paragraph,tabs.text.tab-2)",
    "Text selected -> value -> Details text authored",
    "tc-023 / absent -> absent",
  ],
  [
    "tc-025-reselect-outer-two",
    "p1/0",
    "click(S.selectBlock(palette.outerTabs))",
    "child authored -> selected state -> outer selected",
    "tc-024 / absent -> absent",
  ],
  [
    "tc-026-edit-history",
    "p1/0",
    'click(S.editTab("History"))',
    "outer selected -> active slot -> tab-3 armed",
    "tc-025 / absent -> absent",
  ],
  [
    "tc-027-text-three-before",
    "p1/0",
    "blocksBefore(palette.tabThreeText)",
    "tab-3 armed -> ID set + Insert selected -> Text baseline captured",
    "tc-026 / absent -> absent",
  ],
  [
    "tc-028-text-three-click",
    "p1/0",
    'click(S.palette("Text"))',
    "baseline -> click -> Text inserted in tab-3",
    "tc-027 / absent -> absent",
  ],
  [
    "tc-029-text-three-capture",
    "p1/0",
    'captureNew(palette.tabThreeText,"text",tc-027)',
    "insertion settled -> one ID -> tab-3 Text frozen",
    "tc-027,tc-028 / absent -> absent",
  ],
  [
    "tc-030-text-three-fill",
    "p1/0",
    "fill(S.paragraph,tabs.text.tab-3)",
    "Text selected -> value -> History text authored",
    "tc-029 / absent -> absent",
  ],
  [
    "tc-031-save",
    "p1/0",
    "click(S.builderSave)",
    "three tabs/text dirty -> save settlement -> builder clean",
    "tc-030 / absent -> absent",
  ],
  [
    "tc-032-list",
    "p1/0",
    "goto(paths.screens)",
    "builder clean -> URL -> Screen list",
    "tc-031 / absent -> absent",
  ],
  [
    "tc-032a-auth-rate-window-barrier",
    "p1/0",
    "authRateWindowBarrier()",
    'Screen list stable/bounded rate epoch -> configured auth window naturally expires when enabled or timer is skipped when disabled + bounded realm-stability proof -> exact `{"barrierSatisfied":true}`',
    "tc-032 / absent -> absent",
  ],
  [
    "tc-033-reopen",
    "p1/0",
    "goto(paths.builder)",
    "list -> URL/canvas -> builder reopened",
    "tc-032a-auth-rate-window-barrier / absent -> absent",
  ],
  [
    "tc-034-three-tabs",
    "p1/0",
    "assert(three-tabs-persisted)",
    "reopened -> tab/slot/nested DOM + read -> exact persisted structure",
    "tc-033 / absent -> absent",
  ],
  [
    "tc-035-click-details",
    "p1/0",
    'click(S.scopedRuntimeTab(palette.outerTabs,"Details"))',
    "Overview active -> selected state -> Details active",
    "tc-034 / absent -> absent",
  ],
  [
    "tc-036-details-state",
    "p1/0",
    "observe(outer-tabs-details-state)",
    "Details active -> geometry/hidden/armed -> Details sample frozen",
    "tc-035 / absent -> absent",
  ],
  [
    "tc-037-click-history",
    "p1/0",
    'click(S.scopedRuntimeTab(palette.outerTabs,"History"))',
    "Details active -> selected state -> History active",
    "tc-036 / absent -> absent",
  ],
  [
    "tc-038-history-state",
    "p1/0",
    "observe(outer-tabs-history-state)",
    "History active -> geometry/hidden/armed -> History sample frozen",
    "tc-037 / absent -> absent",
  ],
  [
    "tc-039-one-panel",
    "p1/0",
    "assert(one-panel-visible)",
    "two samples/current DOM -> strict geometry -> exactly one visible",
    "tc-036,tc-038 / absent -> absent",
  ],
  [
    "tc-040-hidden-panels",
    "p1/0",
    "assert(other-panels-zero-geometry)",
    "current History -> hidden/rects -> other panels zero",
    "tc-038 / absent -> absent",
  ],
  [
    "tc-041-armed-slot",
    "p1/0",
    "assert(armed-slot-equals-active-tab)",
    "Details+History samples -> IDs -> armed equals active both directions",
    "tc-036,tc-038 / absent -> absent",
  ],
  [
    "tc-042-shot",
    "p1/0",
    "screen(tabs-content-dark)",
    "assertions pass -> PNG -> tabs-content screenshot created",
    "tc-039,tc-040,tc-041 / absent -> absent",
  ],
  [
    "tc-043-log-agg-errors",
    "p1/0",
    "logs(aggregate,console-errors)",
    "flow complete -> `[]` -> aggregate clean",
    "tc-042 / absent -> absent",
  ],
  [
    "tc-044-log-pages-errors",
    "p1/0",
    "logs(per-page,console-errors)",
    "logger stable -> every page `[]` -> pages clean",
    "tc-043 / absent -> absent",
  ],
  [
    "tc-045-log-agg-warnings",
    "p1/0",
    "logs(aggregate,console-warnings)",
    "flow complete -> `[]` -> aggregate clean",
    "tc-044 / absent -> absent",
  ],
  [
    "tc-046-log-pages-warnings",
    "p1/0",
    "logs(per-page,console-warnings)",
    "logger stable -> every page `[]` -> pages clean",
    "tc-045 / absent -> absent",
  ],
  [
    "tc-047-log-agg-page-errors",
    "p1/0",
    "logs(aggregate,page-errors)",
    "flow complete -> `[]` -> aggregate clean",
    "tc-046 / absent -> absent",
  ],
  [
    "tc-048-log-pages-page-errors",
    "p1/0",
    "logs(per-page,page-errors)",
    "logger stable -> every page `[]` -> flow 2 clean",
    "tc-047 / absent -> absent",
  ]
];
