import { deepFreezeExact } from "../core.mjs";

// Canonical raw action rows for the TASK-540 setup flow.
// The owning module freezes its rows before composition and manifest validation.
export const SETUP_ACTION_ROWS = deepFreezeExact([
  [
    "set-001-storage-preflight",
    "runtime",
    "storage(preflight-and-snapshot)",
    'helper stopped/no task-UA request issued -> first sub-proof requires exact persisted `setup.completed:true`, freezes the exact canonical bootstrap Admin identity/role, exact task-UA access/audit-log and exact task-User-Agent bounded session baseline, plus proof-only complete `site.contentRoutes` row/absence with all task slugs absent; validates exact-one persisted `storage.driver:"local"` and private `storage.local.dir` rows equal top-level local config + `MEDIA_STORAGE`/`MEDIA_DIR` absent, then freezes the bound storage DB/root baseline; egress exact missing row/file zero only -> setup/bootstrap/routes/storage proven',
    "- / absent -> absent",
  ],
  [
    "set-002-helper-launch",
    "runtime",
    "host(helper-launch)",
    "storage proven, ports absent -> owned PID/lineage -> host starting",
    "set-001 / absent -> absent",
  ],
  [
    "set-003-admin-health",
    "runtime",
    "health(admin)",
    "owned host -> status -> Admin healthy",
    "set-002 / absent -> absent",
  ],
  [
    "set-004-front-health",
    "runtime",
    "health(front)",
    "Admin healthy -> status -> front healthy",
    "set-003 / absent -> absent",
  ],
  [
    "set-004a-bot-protection-preflight",
    "runtime",
    "apiPublicRead(auth-bot-protection)",
    'host healthy/no login attempted -> strict four-key public response/private fields -> sanitized exact `{"enabled":false}` or infrastructure fail',
    "set-004 / absent -> absent",
  ],
  [
    "set-004b-session-policy-preflight",
    "runtime",
    "settingsRead(session-policy)",
    'bot protection disabled -> WeakMap-private session policy + validated exact `security.csrf.headerName` -> sanitized exact `{"singleSession":false,"effectiveMaxPerUserAtLeast2":true}` or infrastructure fail',
    "set-004a-bot-protection-preflight / absent -> absent",
  ],
  [
    "set-004c-auth-rate-budget-preflight",
    "runtime",
    "settingsRead(auth-rate-budget)",
    "session policy proven -> exact active auth bucket projection + frozen identity/window budget computation -> capacity proven or infrastructure fail",
    "set-004b-session-policy-preflight / absent -> absent",
  ],
  [
    "set-005-open",
    "p1/0",
    "open(about:blank)",
    "auth/session/rate preflights proven -> page identity -> original page open",
    "set-004c-auth-rate-budget-preflight / absent -> absent",
  ],
  [
    "set-006-logger",
    "p1/0",
    "logger-install",
    "blank original -> exact unique browser User-Agent applied before network + `true` -> immutable context logger/navigation/auth-challenge tracker",
    "set-005 / absent -> absent",
  ],
  [
    "set-007-goto-login",
    "p1/0",
    "goto(paths.screens)",
    "logger installed + setup preflight proven -> URL -> login only; wizard is forbidden",
    "set-006 / absent -> absent",
  ],
  [
    "set-008-resize",
    "p1/0",
    "resize(1280,900)",
    "login visible/wizard absent -> viewport -> 1280x900",
    "set-007 / absent -> absent",
  ],
  [
    "set-009-login-email",
    "p1/0",
    "fill(S.loginEmail,$ADMIN_EMAIL)",
    "login visible -> discarded -> email filled",
    "set-008 / absent -> absent",
  ],
  [
    "set-010-login-password",
    "p1/0",
    "fill(S.loginPassword,$ADMIN_PASSWORD)",
    "email filled -> discarded -> credentials filled",
    "set-009 / absent -> absent",
  ],
  [
    "set-011-login-submit",
    "p1/0",
    "click(S.loginSubmit)",
    "credentials filled -> navigation -> bootstrap authenticated",
    "set-010 / absent -> absent",
  ],
  [
    "set-011a-bootstrap-auth-settled",
    "p1/0",
    "observe(bootstrap-auth-identity-settled)",
    "submit navigation started -> post-login Admin URL + positive-geometry `S.bootstrapUserMenu` -> bootstrap realm settled",
    "set-011 / absent -> absent",
  ],
  [
    "set-011b-bootstrap-api-login",
    "runtime",
    "isolatedApiSessionLogin(bootstrap)",
    "bootstrap UI identity settled -> one login in empty isolated jar + exact session-row inventory -> isolated bootstrap API session acquired",
    "set-011a-bootstrap-auth-settled / absent -> absent",
  ],
  [
    "set-011c-bootstrap-csrf-capture",
    "runtime",
    "isolatedApiSessionCsrfCapture(bootstrap)",
    "isolated bootstrap session acquired -> one CSRF request/private rotated capability -> bootstrap unsafe API actions authorized without changing the browser jar",
    "set-011b-bootstrap-api-login / absent -> absent",
  ],
  [
    "set-012-user-a-create",
    "runtime",
    "fixture(create-user-a)",
    "bootstrap API capability proven -> captured server ID -> user A acquired",
    "set-011c-bootstrap-csrf-capture / absent -> absent",
  ],
  [
    "set-013-user-a-proof",
    "runtime",
    "fixtureRead(user-a)",
    "user A acquired -> exact safe projection/Admin role -> user A proven",
    "set-012 / absent -> absent",
  ],
  [
    "set-014-user-b-create",
    "runtime",
    "fixture(create-user-b)",
    "user A proven -> captured server ID -> user B acquired",
    "set-013 / absent -> absent",
  ],
  [
    "set-015-user-b-proof",
    "runtime",
    "fixtureRead(user-b)",
    "user B acquired -> exact safe projection/Admin role -> users proven",
    "set-014 / absent -> absent",
  ],
  [
    "set-016-editable-type-create",
    "runtime",
    "api(create-content-type-editable)",
    "users proven/exact names+configuration body without field IDs -> captured ID + exact authored slug -> editable schema acquired",
    "set-015 / absent -> absent",
  ],
  [
    "set-017-editable-type-proof",
    "runtime",
    "apiRead(content-type-editable)",
    "editable schema acquired -> exact nine names/configs + canonical `fieldsFromSchema()` IDs -> editable schema proven",
    "set-016 / absent -> absent",
  ],
  [
    "set-018-related-a-type-create",
    "runtime",
    "api(create-content-type-related-a)",
    "editable schema proven/exact names+configuration body without field IDs -> captured ID + exact authored slug -> A schema acquired",
    "set-017 / absent -> absent",
  ],
  [
    "set-019-related-a-type-proof",
    "runtime",
    "apiRead(content-type-related-a)",
    "A schema acquired -> exact field/slug + canonical `field-label` reconstruction -> A schema proven",
    "set-018 / absent -> absent",
  ],
  [
    "set-020-related-b-type-create",
    "runtime",
    "api(create-content-type-related-b)",
    "A schema proven/exact names+configuration body without field IDs -> captured ID + exact authored slug -> B schema acquired",
    "set-019 / absent -> absent",
  ],
  [
    "set-021-related-b-type-proof",
    "runtime",
    "apiRead(content-type-related-b)",
    "B schema acquired -> exact field/slug + canonical `field-label` reconstruction -> all schemas proven",
    "set-020 / absent -> absent",
  ],
  [
    "set-021a-related-failure-type-create",
    "runtime",
    "api(create-content-type-related-failure)",
    "A/B schemas proven/exact names+configuration body without field IDs -> captured ID + exact authored slug -> failure schema acquired",
    "set-021 / absent -> absent",
  ],
  [
    "set-021b-related-failure-type-proof",
    "runtime",
    "apiRead(content-type-related-failure)",
    "failure schema acquired -> exact field/slug + canonical `field-label` reconstruction -> all four schemas proven",
    "set-021a-related-failure-type-create / absent -> absent",
  ],
  [
    "set-022-related-a1-create",
    "runtime",
    "api(create-related-entry-a1)",
    "A schema proven/exact title+slug+data body -> captured ID -> A1 acquired",
    "set-021b-related-failure-type-proof / absent -> absent",
  ],
  [
    "set-023-related-a1-proof",
    "runtime",
    "apiRead(related-entry-a1)",
    "A1 acquired -> exact title/slug/data -> A1 proven",
    "set-022 / absent -> absent",
  ],
  [
    "set-024-related-a2-create",
    "runtime",
    "api(create-related-entry-a2)",
    "A1 proven/exact title+slug+data body -> captured ID -> A2 acquired",
    "set-023 / absent -> absent",
  ],
  [
    "set-025-related-a2-proof",
    "runtime",
    "apiRead(related-entry-a2)",
    "A2 acquired -> exact title/slug/data -> A2 proven",
    "set-024 / absent -> absent",
  ],
  [
    "set-026-related-b1-create",
    "runtime",
    "api(create-related-entry-b1)",
    "A entries proven/exact title+slug+data body -> captured ID -> B1 acquired",
    "set-025 / absent -> absent",
  ],
  [
    "set-027-related-b1-proof",
    "runtime",
    "apiRead(related-entry-b1)",
    "B1 acquired -> exact title/slug/data -> B1 proven",
    "set-026 / absent -> absent",
  ],
  [
    "set-028-related-b2-create",
    "runtime",
    "api(create-related-entry-b2)",
    "B1 proven/exact title+slug+data body -> captured ID -> B2 acquired",
    "set-027 / absent -> absent",
  ],
  [
    "set-029-related-b2-proof",
    "runtime",
    "apiRead(related-entry-b2)",
    "B2 acquired -> exact title/slug/data -> A/B related entries proven",
    "set-028 / absent -> absent",
  ],
  [
    "set-029a-related-failure1-create",
    "runtime",
    "api(create-related-entry-failure1)",
    "failure schema proven/exact title+slug+data body -> captured ID -> failure entry acquired",
    "set-029 / absent -> absent",
  ],
  [
    "set-029b-related-failure1-proof",
    "runtime",
    "apiRead(related-entry-failure1)",
    "failure entry acquired -> exact title/slug/data -> all related entries proven",
    "set-029a-related-failure1-create / absent -> absent",
  ],
  [
    "set-030-media-upload",
    "runtime",
    "api(upload-fixture-png)",
    "local snapshot held + exact deep-frozen blueprint base64/68-byte/PNG-signature/SHA-256 authority -> one real multipart upload + media ID/URL/key -> media acquired",
    "set-029b-related-failure1-proof / absent -> absent",
  ],
  [
    "set-031-media-proof",
    "runtime",
    "apiRead(media-detail)",
    "media acquired -> exact safe projection -> media proven",
    "set-030 / absent -> absent",
  ],
  [
    "set-032-storage-post-setup",
    "runtime",
    "storage(post-setup-stable-observation)",
    "media proven -> exact zero egress + private snapshots -> owned delta frozen",
    "set-031 / absent -> absent",
  ],
  [
    "set-033-entry-create",
    "runtime",
    "api(create-editable-entry)",
    "all value refs bound/exact title+slug+data body -> captured entry ID -> baseline entry acquired",
    "set-032 / absent -> absent",
  ],
  [
    "set-034-entry-proof",
    "runtime",
    "apiRead(editable-entry)",
    "entry acquired -> exact title/slug/baseline data -> entry proven",
    "set-033 / absent -> absent",
  ],
  [
    "set-035-screen-create",
    "runtime",
    "api(create-screen-definition)",
    "entry/schema proven -> materialized/strict-validated concrete listView + one POST/captured Screen ID -> deterministic main document acquired",
    "set-034 / absent -> absent",
  ],
  [
    "set-036-screen-proof",
    "runtime",
    "apiRead(screen-definition)",
    "Screen acquired -> byte-identical concrete listView/Image/related-list data/IDs/bindings -> main Screen proven",
    "set-035 / absent -> absent",
  ],
  [
    "set-037-retry-screen-create",
    "runtime",
    "api(create-retry-screen-definition)",
    "main Screen proven -> independently materialized/strict-validated concrete listView + one POST/captured retry Screen ID -> retry-only document acquired",
    "set-036 / absent -> absent",
  ],
  [
    "set-038-retry-screen-proof",
    "runtime",
    "apiRead(retry-screen-definition)",
    "retry Screen acquired -> byte-identical concrete listView + exact one failure related-list/no Field blocks -> retry Screen proven",
    "set-037 / absent -> absent",
  ],
  [
    "set-039-override-create",
    "runtime",
    "api(replace-direct-image-safe-override)",
    "main Screen/entry/media proven -> one write -> acquired-media override stored",
    "set-038 / absent -> absent",
  ],
  [
    "set-040-override-proof",
    "runtime",
    "apiRead(direct-image-safe-override)",
    "override stored -> exact one scoped tuple -> media-race projection proven",
    "set-039 / absent -> absent",
  ],
  [
    "set-041-preference-a",
    "runtime",
    "fixture(set-user-a-preference-false)",
    "user A proven/strict domain-normalized false -> one local `setUserSetting` call -> exact A composite setting stored",
    "set-040 / absent -> absent",
  ],
  [
    "set-042-preference-a-proof",
    "runtime",
    "fixtureRead(user-a-preference)",
    "A composite setting stored -> one local `getUserSetting` + strict normalized literal `false` -> A baseline proven",
    "set-041 / absent -> absent",
  ],
  [
    "set-043-preference-b",
    "runtime",
    "fixture(set-user-b-preference-false)",
    "user B proven/strict domain-normalized false -> one local `setUserSetting` call -> exact B composite setting stored",
    "set-042 / absent -> absent",
  ],
  [
    "set-044-preference-b-proof",
    "runtime",
    "fixtureRead(user-b-preference)",
    "B composite setting stored -> one local `getUserSetting` + strict normalized literal `false` -> fixtures ready",
    "set-043 / absent -> absent",
  ],
  [
    "set-045-builder-cold",
    "p1/0",
    "goto(paths.builder)",
    "fixtures ready, no entry/media consumer visited -> URL/marker -> cold builder visible",
    "set-044 / absent -> absent",
  ]
]);
