import type { Task551SanitizedCatalogProjectionV1 } from "./digestContract";

export const TASK551_REQUIRED_SANITIZED_CATALOG_PROJECTION_LITERAL: Task551SanitizedCatalogProjectionV1 =
  {
    version: "task551-sanitized-catalog@v1",
    tables: [
      {
        schema: "public",
        name: "users",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "email", postgresType: "text", nullable: false },
          { name: "name", postgresType: "text", nullable: true },
          { name: "status", postgresType: "text", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "roles",
        columns: [{ name: "id", postgresType: "uuid", nullable: false }],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "user_roles",
        columns: [
          { name: "user_id", postgresType: "uuid", nullable: false },
          { name: "role_id", postgresType: "uuid", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "pages",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "title", postgresType: "text", nullable: false },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "author_id", postgresType: "uuid", nullable: true },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [
          {
            name: "pages_author_id_users_id_fk",
            kind: "foreign-key",
            columns: ["author_id"],
            referencedTable: "users",
            referencedColumns: ["id"],
          },
        ],
        indexes: [],
      },
      {
        schema: "public",
        name: "content_types",
        columns: [{ name: "id", postgresType: "uuid", nullable: false }],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "content_entries",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "type_id", postgresType: "uuid", nullable: false },
          { name: "author_id", postgresType: "uuid", nullable: true },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "title", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "visibility", postgresType: "text", nullable: false },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "posts",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "author_id", postgresType: "uuid", nullable: true },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "title", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "tags", postgresType: "jsonb", nullable: false },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "forms",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "name", postgresType: "text", nullable: false },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "form_submissions",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "form_id", postgresType: "uuid", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "media",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "key", postgresType: "text", nullable: false },
          { name: "type", postgresType: "text", nullable: false },
          { name: "mime_type", postgresType: "text", nullable: false },
          { name: "title", postgresType: "text", nullable: true },
          { name: "tags", postgresType: "jsonb", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "bookings",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "service_id", postgresType: "uuid", nullable: false },
          { name: "resource_id", postgresType: "uuid", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "starts_at", postgresType: "timestamp", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "booking_resources",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "name", postgresType: "text", nullable: false },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "type", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "booking_services",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "name", postgresType: "text", nullable: false },
          { name: "slug", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "updated_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "booking_blackouts",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "resource_id", postgresType: "uuid", nullable: true },
          { name: "starts_at", postgresType: "timestamp", nullable: false },
          { name: "ends_at", postgresType: "timestamp", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "booking_service_resources",
        columns: [
          { name: "service_id", postgresType: "uuid", nullable: false },
          { name: "resource_id", postgresType: "uuid", nullable: false },
          { name: "is_required", postgresType: "bool", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "booking_schedules",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "resource_id", postgresType: "uuid", nullable: false },
          { name: "day_of_week", postgresType: "int4", nullable: false },
          { name: "start_minute", postgresType: "int4", nullable: false },
          { name: "end_minute", postgresType: "int4", nullable: false },
          { name: "is_available", postgresType: "bool", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "password_resets",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "user_id", postgresType: "uuid", nullable: false },
          { name: "expires_at", postgresType: "timestamp", nullable: false },
          { name: "used_at", postgresType: "timestamp", nullable: true },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "preview_tokens",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "target_id", postgresType: "uuid", nullable: false },
          { name: "expires_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "post_preview_tokens",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "post_id", postgresType: "uuid", nullable: false },
          { name: "expires_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "assistant_doc_ingest_runs",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "source_root", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
          { name: "started_at", postgresType: "timestamp", nullable: false },
          { name: "finished_at", postgresType: "timestamp", nullable: true },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "form_action_runs",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "submission_id", postgresType: "uuid", nullable: true },
          { name: "action_id", postgresType: "uuid", nullable: true },
          { name: "status", postgresType: "text", nullable: false },
          { name: "created_at", postgresType: "timestamp", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "solution_kit_install_runs",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "kit_id", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
      {
        schema: "public",
        name: "solution_kit_install_items",
        columns: [
          { name: "id", postgresType: "uuid", nullable: false },
          { name: "run_id", postgresType: "uuid", nullable: false },
          { name: "position", postgresType: "int4", nullable: false },
          { name: "operation", postgresType: "text", nullable: false },
          { name: "status", postgresType: "text", nullable: false },
        ],
        constraints: [],
        indexes: [],
      },
    ],
  };
