/**
 * Stable public facade for the Page document v2 contract.
 *
 * Keep implementation ownership in the focused modules below. Consumers should
 * continue importing this facade so the split remains an internal detail.
 */
export {
  ANIMATED_ICON_NAME_PATTERN,
  ANIMATED_ICON_SIZE_CLAMP,
  ANIMATED_ICON_SPEED_CLAMP,
  GALLERY_CATEGORY_PATTERN,
  GALLERY_FILTER_CATEGORY_MAX,
  PAGE_BLOCK_BORDER_WIDTH_CLAMP,
  PAGE_BLOCK_BOX_SPACING_CLAMP,
  PAGE_BLOCK_MAX_CHILDREN_PER_SLOT,
  PAGE_BLOCK_MAX_TREE_DEPTH,
  PAGE_BLOCK_SPAN_CLAMP,
  PAGE_COLLECTION_LIMIT_CLAMP,
  PAGE_CUSTOM_SVG_MAX_BYTES,
  PAGE_DECORATION_DELAY_CLAMP,
  PAGE_DECORATION_DURATION_CLAMP,
  PAGE_DIVIDER_WIDTH_CLAMP,
  PAGE_DOCUMENT_SCHEMA_VERSION,
  PAGE_DRAW_SPEED_CLAMP,
  PAGE_FILTERS_MAX_FACETS,
  PAGE_GLOW_BLUR_CLAMP,
  PAGE_GLOW_OFFSET_CLAMP,
  PAGE_GLOW_SPREAD_CLAMP,
  PAGE_LAYER_X_CLAMP,
  PAGE_LAYER_Y_CLAMP,
  PAGE_LAYER_Z_CLAMP,
  PAGE_MARQUEE_SPEED_CLAMP,
  PAGE_PARALLAX_INTENSITY_CLAMP,
  PAGE_REVEAL_DELAY_CLAMP,
  PAGE_SECTION_BLOCK_COLUMN_CLAMP,
  PAGE_SECTION_BORDER_WIDTH_CLAMP,
  PAGE_SPOTLIGHT_SIZE_CLAMP,
  PAGE_SWITCHER_ARIA_LABEL_MAX_LENGTH,
  PAGE_SWITCHER_DEFAULT_ARIA_LABEL,
  PAGE_TEXT_MARK_MAX,
  PAGE_TYPOGRAPHY_LETTER_SPACING_CLAMP,
  PAGE_TYPOGRAPHY_LINE_HEIGHT_CLAMP,
  SWITCHER_MAX_PANELS,
  PageDocumentError,
  animatedIconAnimations,
  animatedIconNames,
  isPageTextColorMarkCapableBlockType,
  isPageTextMarkCapableBlockType,
  isPageTypographyCapableBlockType,
  normalizeSwitcherAriaLabel,
  pageBackgroundTypes,
  pageBadgeIconPositions,
  pageBadgeIcons,
  pageBadgeShapes,
  pageBadgeSizes,
  pageBadgeVariants,
  pageBadgeWeights,
  pageBlockBorderStyles,
  pageBlockDecorationMotions,
  pageBlockHoverEffects,
  pageBlockSlotKeys,
  pageBlockTypes,
  pageBlockWidths,
  pageBreakpoints,
  pageButtonSizes,
  pageButtonTargets,
  pageButtonVariants,
  pageCollectionPaginationModes,
  pageColumnDistributions,
  pageColumnTemplatePresets,
  pageCompositions,
  pageDividerAligns,
  pageDividerTones,
  pageFiltersBlockLayouts,
  pageFiltersFacetKinds,
  pageFiltersFacetOperators,
  pageGalleryLayouts,
  pageGroupDirections,
  pageHeadingLevels,
  pageImageFits,
  pageLayerAnchors,
  pageMarqueeDirections,
  pageSectionAlignments,
  pageSectionJustify,
  pageSectionScrollEffects,
  pageSectionTypes,
  pageSectionVariants,
  pageShadowTokens,
  pageSurfacePresets,
  pageTextAlignments,
  pageTextColorMarkCapableBlockTypes,
  pageTextFormats,
  pageTextMarkCapableBlockTypes,
  pageTiltStrengths,
  pageTypographyCapableBlockTypes,
  pageTypographyFontFamilies,
  pageTypographyFontFamilyCssValues,
  pageTypographyFontSizeCssValues,
  pageTypographyFontSizes,
  pageTypographyFontWeightCssValues,
  pageTypographyFontWeights,
  pageTypographyTextTransforms,
  resolveAnimatedIconName,
  resolveSwitcherAriaLabel,
  scrollHintGlyphs,
  switcherVariants,
  type AnimatedIconAnimation,
  type AnimatedIconName,
  type PageBackgroundType,
  type PageBadgeIcon,
  type PageBadgeIconPosition,
  type PageBadgeShape,
  type PageBadgeSize,
  type PageBadgeVariant,
  type PageBadgeWeight,
  type PageBlockBorderStyle,
  type PageBlockDecoration,
  type PageBlockDecorationMotion,
  type PageBlockHoverEffect,
  type PageBlockLayer,
  type PageBlockMarquee,
  type PageBlockResponsiveOverrideV2,
  type PageBlockSlotKey,
  type PageBlockStyleV2,
  type PageBlockType,
  type PageBlockV2,
  type PageBlockVisibilityV2,
  type PageBlockWidth,
  type PageBoxSpacingV2,
  type PageBreakpoint,
  type PageCollectionLinkV2,
  type PageCollectionPaginationMode,
  type PageColumnDistribution,
  type PageComposition,
  type PageDocumentErrorCode,
  type PageDocumentSeoV2,
  type PageDocumentSettingsV2,
  type PageDocumentV2,
  type PageEffectsV2,
  type PageGlow,
  type PageGroupDirection,
  type PageLayerAnchor,
  type PageMarqueeDirection,
  type PageScrollHintGlyph,
  type PageSectionAlignment,
  type PageSectionBorderEdgeV2,
  type PageSectionBorderV2,
  type PageSectionJustify,
  type PageSectionLayoutV2,
  type PageSectionResponsiveOverrideV2,
  type PageSectionScrollEffect,
  type PageSectionSpacingV2,
  type PageSectionStyleV2,
  type PageSectionType,
  type PageSectionV2,
  type PageSectionVariant,
  type PageSectionVisibilityV2,
  type PageShadowToken,
  type PageSurfacePreset,
  type PageSwitcherVariant,
  type PageTextColorMark,
  type PageTextColorMarkCapableBlockType,
  type PageTextHighlightMark,
  type PageTextLinkMark,
  type PageTextMark,
  type PageTextMarkCapableBlockType,
  type PageTextStructuralMark,
  type PageTiltStrength,
  type PageTypographyCapableBlockType,
  type PageTypographyFontFamily,
  type PageTypographyFontSize,
  type PageTypographyFontWeight,
  type PageTypographyTextTransform,
} from "./pageDocumentV2Types";

export {
  createPageListItem,
  getPageBlockActiveSlotKeys,
  pageBlockCapabilities,
  pageBlockDefaultProps,
  pageBlockPropKeys,
  pageSectionCapabilities,
  type PageBlockCapabilitiesV2,
  type PageBlockPublicDataBinding,
  type PageBlockRuntimeRendererState,
  type PageListItemV2,
  type PageSectionCapabilitiesV2,
} from "./pageDocumentV2Contract";

export { pageDocumentV2JsonSchema } from "./pageDocumentV2Schema";

export {
  applyBlockTextMark,
  normalizeBlockTextColorMarks,
  normalizeBlockTextMarks,
  removeBlockTextMark,
  type PageBlockTextMarkInput,
  type PageBlockTextMarkRemoveInput,
} from "./pageTextMarksV2";

export {
  clearBlockResponsiveOverride,
  clearResponsiveOverride,
  createDefaultPageDocumentV2,
  createPageBlockV2,
  createPageDocumentId,
  createPageSectionV2,
  isLegacyOrVersionlessPageDocument,
  isPageDocumentError,
  normalizePageDocumentV2,
  normalizePageDocumentV2ForWrite,
  normalizeStoredPageDocumentV2ForRead,
  resolvePageBlockForBreakpoint,
  resolvePageDocumentForBreakpoint,
  resolvePageSectionForBreakpoint,
  toPublishedPageDocumentV2,
} from "./pageDocumentV2Normalizer";
