import {
  PAGE_BLOCK_BORDER_WIDTH_CLAMP,
  PAGE_BLOCK_SPAN_CLAMP,
  PAGE_GLOW_BLUR_CLAMP,
  PAGE_GLOW_OFFSET_CLAMP,
  PAGE_GLOW_SPREAD_CLAMP,
  PAGE_LAYER_Z_CLAMP,
  PAGE_TYPOGRAPHY_LETTER_SPACING_CLAMP,
  PAGE_TYPOGRAPHY_LINE_HEIGHT_CLAMP,
  pageBackgroundTypes,
  pageBlockBorderStyles,
  pageBlockDecorationMotions,
  pageBlockHoverEffects,
  pageBlockWidths,
  pageCompositions,
  pageLayerAnchors,
  pageShadowTokens,
  pageSurfacePresets,
  pageTextAlignments,
  pageTiltStrengths,
  pageTypographyFontFamilies,
  pageTypographyFontSizes,
  pageTypographyFontWeights,
  pageTypographyTextTransforms,
  type PageBlockType,
} from "./pageDocumentV2";
import { control, type PageEditorControlDefinition } from "./pageEditorControlDefinition";

export const pageUniversalBlockControls: readonly PageEditorControlDefinition[] = [
  control({
    id: "block.style.width",
    panel: "layout",
    target: "block",
    label: "Width",
    path: ["style", "width"],
    input: "segmented",
    responsive: true,
    options: pageBlockWidths,
  }),
  control({
    id: "block.style.align",
    panel: "layout",
    target: "block",
    label: "Align",
    path: ["style", "align"],
    input: "segmented",
    responsive: true,
    options: pageTextAlignments,
  }),
  control({
    id: "block.style.textColor",
    panel: "style",
    target: "block",
    label: "Text color",
    path: ["style", "textColor"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "block.style.background",
    panel: "background",
    target: "block",
    label: "Background",
    path: ["style", "background"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "block.style.backgroundType",
    panel: "background",
    target: "block",
    label: "Background type",
    path: ["style", "backgroundType"],
    input: "select",
    responsive: true,
    options: pageBackgroundTypes,
    fallback: "none",
  }),
  control({
    id: "block.style.backgroundImage",
    panel: "background",
    target: "block",
    label: "Background image",
    path: ["style", "backgroundImage"],
    input: "media",
    responsive: true,
  }),
  control({
    id: "block.style.opacity",
    panel: "style",
    target: "block",
    label: "Opacity",
    path: ["style", "opacity"],
    input: "number",
    responsive: true,
    clamp: { min: 0, max: 1 },
    fallback: 1,
  }),
  control({
    id: "block.style.radius",
    panel: "style",
    target: "block",
    label: "Radius",
    path: ["style", "radius"],
    input: "number",
    responsive: true,
    clamp: { min: 0, max: 64 },
    fallback: 0,
  }),
  control({
    id: "block.style.shadow",
    panel: "style",
    target: "block",
    label: "Shadow",
    path: ["style", "shadow"],
    input: "select",
    responsive: true,
    options: pageShadowTokens,
    fallback: "none",
  }),
  control({
    id: "block.style.glow.color",
    panel: "style",
    target: "block",
    label: "Glow color",
    path: ["style", "glow", "color"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "block.style.glow.blur",
    panel: "style",
    target: "block",
    label: "Glow blur",
    path: ["style", "glow", "blur"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_BLUR_CLAMP.min, max: PAGE_GLOW_BLUR_CLAMP.max },
  }),
  control({
    id: "block.style.glow.spread",
    panel: "style",
    target: "block",
    label: "Glow spread",
    path: ["style", "glow", "spread"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_SPREAD_CLAMP.min, max: PAGE_GLOW_SPREAD_CLAMP.max },
  }),
  control({
    id: "block.style.glow.x",
    panel: "style",
    target: "block",
    label: "Glow offset X",
    path: ["style", "glow", "x"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_OFFSET_CLAMP.min, max: PAGE_GLOW_OFFSET_CLAMP.max },
  }),
  control({
    id: "block.style.glow.y",
    panel: "style",
    target: "block",
    label: "Glow offset Y",
    path: ["style", "glow", "y"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_OFFSET_CLAMP.min, max: PAGE_GLOW_OFFSET_CLAMP.max },
  }),
  control({
    id: "block.style.borderColor",
    panel: "style",
    target: "block",
    label: "Border color",
    path: ["style", "borderColor"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "block.style.borderWidth",
    panel: "style",
    target: "block",
    label: "Border width",
    path: ["style", "borderWidth"],
    input: "number",
    responsive: true,
    clamp: PAGE_BLOCK_BORDER_WIDTH_CLAMP,
    fallback: 0,
  }),
  control({
    id: "block.style.borderStyle",
    panel: "style",
    target: "block",
    label: "Border style",
    path: ["style", "borderStyle"],
    input: "segmented",
    responsive: true,
    options: pageBlockBorderStyles,
    fallback: "none",
  }),
  ...(["top", "right", "bottom", "left"] as const).flatMap((side) => [
    control({
      id: `block.style.padding.${side}`,
      panel: "spacing",
      target: "block",
      label: `Padding ${side}`,
      path: ["style", "padding", side],
      input: "number",
      responsive: true,
      clamp: { min: 0, max: 240 },
      fallback: 0,
    }),
    control({
      id: `block.style.margin.${side}`,
      panel: "spacing",
      target: "block",
      label: `Margin ${side}`,
      path: ["style", "margin", side],
      input: "number",
      responsive: true,
      clamp: { min: 0, max: 240 },
      fallback: 0,
    }),
  ]),
  control({
    id: "block.decoration.motion",
    panel: "style",
    target: "block",
    label: "Decoration motion",
    path: ["style", "decoration", "motion"],
    input: "select",
    responsive: false,
    options: pageBlockDecorationMotions,
  }),
  control({
    id: "block.decoration.delay",
    panel: "style",
    target: "block",
    label: "Decoration delay",
    path: ["style", "decoration", "delay"],
    input: "number",
    responsive: false,
    clamp: { min: 0, max: 4000 },
    unit: "ms",
  }),
  control({
    id: "block.decoration.duration",
    panel: "style",
    target: "block",
    label: "Decoration duration",
    path: ["style", "decoration", "duration"],
    input: "number",
    responsive: false,
    clamp: { min: 2000, max: 16000 },
    unit: "ms",
  }),
  control({
    id: "block.style.revealDelay",
    panel: "style",
    target: "block",
    label: "Reveal delay",
    path: ["style", "revealDelay"],
    input: "number",
    responsive: false,
    clamp: { min: 0, max: 4000 },
    unit: "ms",
  }),
  control({
    id: "block.tilt.strength",
    panel: "style",
    target: "block",
    label: "Mouse tilt (3D)",
    path: ["style", "tilt"],
    input: "select",
    responsive: false,
    options: pageTiltStrengths,
  }),
  control({
    id: "block.tilt.glare",
    panel: "style",
    target: "block",
    label: "Tilt glare",
    path: ["style", "tiltGlare"],
    input: "switch",
    responsive: false,
  }),
  control({
    id: "block.surface.tint",
    panel: "style",
    target: "block",
    label: "Surface tint",
    path: ["style", "surfaceTint"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "block.surface.preset",
    panel: "style",
    target: "block",
    label: "Surface preset",
    path: ["style", "surfacePreset"],
    input: "select",
    responsive: false,
    options: pageSurfacePresets,
  }),
  control({
    id: "block.hover.effect",
    panel: "style",
    target: "block",
    label: "Hover effect",
    path: ["style", "hoverEffect"],
    input: "select",
    responsive: false,
    options: pageBlockHoverEffects,
  }),
  control({
    id: "block.layer.x",
    panel: "layout",
    target: "block",
    label: "Layer X",
    path: ["style", "layer", "x"],
    input: "number",
    responsive: true,
    clamp: { min: -50, max: 150 },
    unit: "%",
  }),
  control({
    id: "block.layer.y",
    panel: "layout",
    target: "block",
    label: "Layer Y",
    path: ["style", "layer", "y"],
    input: "number",
    responsive: true,
    clamp: { min: -50, max: 150 },
    unit: "%",
  }),
  control({
    id: "block.layer.z",
    panel: "layout",
    target: "block",
    label: "Layer Z (stack)",
    path: ["style", "layer", "z"],
    input: "number",
    responsive: true,
    // TASK-539: import the model-owned clamp directly; no `0..40` mirror.
    clamp: PAGE_LAYER_Z_CLAMP,
    unit: "",
  }),
  control({
    id: "block.layer.anchor",
    panel: "layout",
    target: "block",
    label: "Layer anchor",
    path: ["style", "layer", "anchor"],
    input: "select",
    responsive: false,
    options: pageLayerAnchors,
    fallback: "top-left",
  }),
  control({
    id: "block.style.magnetic",
    panel: "style",
    target: "block",
    label: "Magnetic hover",
    path: ["style", "magnetic"],
    input: "switch",
    responsive: false,
  }),
  control({
    id: "block.visibility.visible",
    panel: "visibility",
    target: "block",
    label: "Visible",
    path: ["visibility", "visible"],
    input: "switch",
    responsive: true,
    fallback: true,
  }),
  control({
    id: "block.style.colSpan",
    panel: "layout",
    target: "block",
    label: "Column span",
    path: ["style", "colSpan"],
    input: "number",
    responsive: true,
    clamp: PAGE_BLOCK_SPAN_CLAMP,
  }),
  control({
    id: "block.style.rowSpan",
    panel: "layout",
    target: "block",
    label: "Row span",
    path: ["style", "rowSpan"],
    input: "number",
    responsive: true,
    clamp: PAGE_BLOCK_SPAN_CLAMP,
  }),
] as const;

export const pageTypographyBlockControls: readonly PageEditorControlDefinition[] = [
  control({
    id: "block.style.fontFamily",
    panel: "typography",
    target: "block",
    label: "Font family",
    path: ["style", "fontFamily"],
    input: "segmented",
    responsive: true,
    options: pageTypographyFontFamilies,
  }),
  control({
    id: "block.style.fontSize",
    panel: "typography",
    target: "block",
    label: "Font size",
    path: ["style", "fontSize"],
    input: "segmented",
    responsive: true,
    options: pageTypographyFontSizes,
  }),
  control({
    id: "block.style.fontSizeCustom",
    panel: "typography",
    target: "block",
    label: "Fluid size",
    path: ["style", "fontSizeCustom"],
    input: "text",
    responsive: true,
  }),
  control({
    id: "block.style.textTransform",
    panel: "typography",
    target: "block",
    label: "Text transform",
    path: ["style", "textTransform"],
    input: "select",
    responsive: true,
    options: pageTypographyTextTransforms,
    fallback: "none",
  }),
  control({
    id: "block.style.fontWeight",
    panel: "typography",
    target: "block",
    label: "Font weight",
    path: ["style", "fontWeight"],
    input: "segmented",
    responsive: true,
    options: pageTypographyFontWeights,
  }),
  control({
    id: "block.style.lineHeight",
    panel: "typography",
    target: "block",
    label: "Line height",
    path: ["style", "lineHeight"],
    input: "number",
    responsive: true,
    clamp: PAGE_TYPOGRAPHY_LINE_HEIGHT_CLAMP,
    step: 0.05,
    unit: "",
  }),
  control({
    id: "block.style.letterSpacing",
    panel: "typography",
    target: "block",
    label: "Letter spacing",
    path: ["style", "letterSpacing"],
    input: "number",
    responsive: true,
    clamp: PAGE_TYPOGRAPHY_LETTER_SPACING_CLAMP,
    step: 0.5,
    unit: "px",
    fallback: 0,
  }),
] as const;

export const blockStyleTextAlignTypographyControl = control({
  id: "block.style.align",
  panel: "typography",
  target: "block",
  label: "Text align",
  path: ["style", "align"],
  input: "segmented",
  responsive: true,
  options: pageTextAlignments,
});

export const styleAlignTypographyBlockTypes = new Set<PageBlockType>([
  "button",
  "list",
  "card",
  "statistic",
  "quote",
]);

export const createLayoutCompositionControl = (
  type: "container" | "columns" | "group"
): PageEditorControlDefinition =>
  control({
    id: `block.${type}.composition.mode`,
    panel: "layout",
    target: "block",
    label: "Composition",
    path: ["style", "composition"],
    input: "select",
    responsive: false,
    options: pageCompositions,
  });
