import {
  PAGE_GLOW_BLUR_CLAMP,
  PAGE_GLOW_OFFSET_CLAMP,
  PAGE_GLOW_SPREAD_CLAMP,
  PAGE_PARALLAX_INTENSITY_CLAMP,
  PAGE_SECTION_BORDER_WIDTH_CLAMP,
  pageBackgroundTypes,
  pageBlockBorderStyles,
  pageColumnTemplatePresets,
  pageCompositions,
  pageSectionAlignments,
  pageSectionJustify,
  pageSectionScrollEffects,
  pageShadowTokens,
  pageSurfacePresets,
  type PageSectionType,
  type PageSectionVariant,
} from "./pageDocumentV2";
import { control, type PageEditorControlDefinition } from "./pageEditorControlDefinition";
import { getPageSectionVariantOptions } from "./pageSectionTemplates";

export const pageUniversalSectionControls: readonly PageEditorControlDefinition[] = [
  control({
    id: "section.layout.columns",
    panel: "layout",
    target: "section",
    label: "Columns",
    path: ["layout", "columns"],
    input: "number",
    responsive: true,
    clamp: { min: 1, max: 4 },
  }),
  control({
    id: "section.layout.maxWidth",
    panel: "layout",
    target: "section",
    label: "Max width",
    path: ["layout", "maxWidth"],
    input: "number",
    responsive: true,
    clamp: { min: 320, max: 1920 },
  }),
  control({
    id: "section.layout.align",
    panel: "layout",
    target: "section",
    label: "Align",
    path: ["layout", "align"],
    input: "segmented",
    responsive: true,
    options: pageSectionAlignments,
  }),
  control({
    id: "section.layout.justify",
    panel: "layout",
    target: "section",
    label: "Justify",
    path: ["layout", "justify"],
    input: "segmented",
    responsive: true,
    options: pageSectionJustify,
  }),
  control({
    id: "section.style.background",
    panel: "background",
    target: "section",
    label: "Background",
    path: ["style", "background"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "section.style.backgroundType",
    panel: "background",
    target: "section",
    label: "Background type",
    path: ["style", "backgroundType"],
    input: "select",
    responsive: true,
    options: pageBackgroundTypes,
  }),
  control({
    id: "section.style.accent",
    panel: "style",
    target: "section",
    label: "Accent",
    path: ["style", "accent"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "section.style.radius",
    panel: "style",
    target: "section",
    label: "Radius",
    path: ["style", "radius"],
    input: "number",
    responsive: true,
    clamp: { min: 0, max: 64 },
  }),
  control({
    id: "section.style.shadow",
    panel: "style",
    target: "section",
    label: "Shadow",
    path: ["style", "shadow"],
    input: "select",
    responsive: true,
    options: pageShadowTokens,
  }),
  control({
    id: "section.style.glow.color",
    panel: "style",
    target: "section",
    label: "Glow color",
    path: ["style", "glow", "color"],
    input: "color",
    responsive: true,
  }),
  control({
    id: "section.style.glow.blur",
    panel: "style",
    target: "section",
    label: "Glow blur",
    path: ["style", "glow", "blur"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_BLUR_CLAMP.min, max: PAGE_GLOW_BLUR_CLAMP.max },
  }),
  control({
    id: "section.style.glow.spread",
    panel: "style",
    target: "section",
    label: "Glow spread",
    path: ["style", "glow", "spread"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_SPREAD_CLAMP.min, max: PAGE_GLOW_SPREAD_CLAMP.max },
  }),
  control({
    id: "section.style.glow.x",
    panel: "style",
    target: "section",
    label: "Glow offset X",
    path: ["style", "glow", "x"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_OFFSET_CLAMP.min, max: PAGE_GLOW_OFFSET_CLAMP.max },
  }),
  control({
    id: "section.style.glow.y",
    panel: "style",
    target: "section",
    label: "Glow offset Y",
    path: ["style", "glow", "y"],
    input: "number",
    responsive: true,
    clamp: { min: PAGE_GLOW_OFFSET_CLAMP.min, max: PAGE_GLOW_OFFSET_CLAMP.max },
  }),
  control({
    id: "section.scrollEffect",
    panel: "style",
    target: "section",
    label: "Scroll effect",
    path: ["style", "scrollEffect"],
    input: "segmented",
    responsive: false,
    options: pageSectionScrollEffects,
  }),
  control({
    id: "section.parallaxIntensity",
    panel: "style",
    target: "section",
    label: "Parallax intensity",
    path: ["style", "parallaxIntensity"],
    input: "number",
    responsive: false,
    clamp: {
      min: PAGE_PARALLAX_INTENSITY_CLAMP.min,
      max: PAGE_PARALLAX_INTENSITY_CLAMP.max,
    },
    unit: "px",
    // TASK-539: reachable only when the base scroll effect is parallax; the
    // effective responsive target can never open or close this base-only gate.
    showWhen: { path: ["style", "scrollEffect"], equals: "parallax" },
  }),
  ...(
    [
      ["paddingTop", "Top"],
      ["paddingBottom", "Bottom"],
      ["paddingLeft", "Left"],
      ["paddingRight", "Right"],
      ["gap", "Gap"],
    ] as const
  ).map(([key, label]) =>
    control({
      id: `section.spacing.${key}`,
      panel: "spacing",
      target: "section",
      label,
      path: ["spacing", key],
      input: "number",
      responsive: true,
      clamp: key === "gap" ? { min: 0, max: 120 } : { min: 0, max: 240 },
    })
  ),
  control({
    id: "section.visibility.visible",
    panel: "visibility",
    target: "section",
    label: "Visible",
    path: ["visibility", "visible"],
    input: "switch",
    responsive: true,
  }),
  control({
    id: "section.visibility.authOnly",
    panel: "visibility",
    target: "section",
    label: "Auth only",
    path: ["visibility", "authOnly"],
    input: "switch",
    responsive: true,
  }),
  control({
    id: "section.layout.stackVertical",
    panel: "responsive",
    target: "section",
    label: "Stack vertically",
    path: ["layout", "stackVertical"],
    input: "switch",
    responsive: true,
  }),
  control({
    id: "section.surface.preset",
    panel: "background",
    target: "section",
    label: "Surface preset",
    path: ["style", "surfacePreset"],
    input: "select",
    responsive: false,
    options: pageSurfacePresets,
  }),
  control({
    id: "section.composition.mode",
    panel: "layout",
    target: "section",
    label: "Composition",
    path: ["style", "composition"],
    input: "select",
    responsive: false,
    options: pageCompositions,
  }),
  control({
    id: "section.style.fullBleed",
    panel: "background",
    target: "section",
    label: "Full-bleed background",
    path: ["style", "fullBleed"],
    input: "switch",
    responsive: false,
  }),
  control({
    id: "section.style.noiseOverlay",
    panel: "background",
    target: "section",
    label: "Grain overlay",
    path: ["style", "noiseOverlay"],
    input: "switch",
    responsive: false,
  }),
  control({
    id: "section.style.columnTemplate",
    panel: "layout",
    target: "section",
    label: "Column ratio",
    path: ["style", "columnTemplate"],
    input: "select",
    responsive: false,
    options: pageColumnTemplatePresets,
  }),
  ...(["top", "right", "bottom", "left"] as const).flatMap((side) => [
    control({
      id: `section.style.border.${side}.color`,
      panel: "style",
      target: "section",
      label: `Border ${side} color`,
      path: ["style", "border", side, "color"],
      input: "color",
      responsive: false,
    }),
    control({
      id: `section.style.border.${side}.width`,
      panel: "style",
      target: "section",
      label: `Border ${side} width`,
      path: ["style", "border", side, "width"],
      input: "number",
      responsive: false,
      clamp: PAGE_SECTION_BORDER_WIDTH_CLAMP,
    }),
    control({
      id: `section.style.border.${side}.style`,
      panel: "style",
      target: "section",
      label: `Border ${side} style`,
      path: ["style", "border", side, "style"],
      input: "segmented",
      responsive: false,
      options: pageBlockBorderStyles,
      fallback: "none",
    }),
  ]),
] as const;

export const pageSectionStackVerticalControl: PageEditorControlDefinition =
  pageUniversalSectionControls.find(
    (definition) => definition.id === "section.layout.stackVertical"
  )!;

export const getPageSectionVariantControl = (
  type: PageSectionType
): PageEditorControlDefinition | null => {
  const options = getPageSectionVariantOptions(type);
  if (options.length === 0) return null;
  return control({
    id: `section.${type}.variant`,
    panel: "layout",
    target: "section",
    label: "Variant",
    path: ["variant"],
    overridePath: ["variant"],
    input: "select",
    responsive: false,
    options,
  });
};

export const isPageSectionVariantOption = (
  type: PageSectionType,
  value: string
): value is PageSectionVariant =>
  getPageSectionVariantOptions(type).includes(value as PageSectionVariant);
