import { deepFreezeExact } from "./core.mjs";

export const RAW_VISIBLE_ASSERTION_ROWS = deepFreezeExact([
  [
    "button-image",
    "persisted-no-empty-binding",
    ["screenId", "hrefBindingCount", "hrefBindingField", "emptyFieldCount"],
  ],
  ["button-image", "safe-link-front-url", ["tagName", "href", "pageUrl"]],
  ["button-image", "unsafe-link-disabled", ["tagName", "ariaDisabled", "href", "anchorCount"]],
  ["button-image", "direct-image-safe-url", ["imageCount", "src", "placeholderVisible"]],
  [
    "button-image",
    "missing-or-unsafe-placeholder",
    ["imageCount", "placeholderVisible", "unsafeUrlPresent"],
  ],
  [
    "button-image",
    "media-field-keeps-uuid",
    ["selectedMediaTitle", "selectedImageSrc", "persistedMediaId", "persistedResolvedUrlPresent"],
  ],
  ["tabs-content", "three-tabs-persisted", ["tabIds", "labels", "slotIds", "nestedText"]],
  ["tabs-content", "one-panel-visible", ["activeTabId", "visiblePanelIds", "visibleRects"]],
  ["tabs-content", "other-panels-zero-geometry", ["hiddenPanelIds", "hiddenValues", "rects"]],
  ["tabs-content", "armed-slot-equals-active-tab", ["activeTabId", "armedSlotId", "selectedTabId"]],
  ["tabs-keyboard-aria", "arrow-home-end-focus", ["steps"]],
  ["tabs-keyboard-aria", "aria-reciprocal", ["pairs", "visiblePanelId", "hiddenPanelIds"]],
  [
    "tabs-keyboard-aria",
    "nested-tabs-isolated",
    ["outerRootId", "innerRootId", "outerSelectedId", "innerSelectedId"],
  ],
  ["tabs-keyboard-aria", "renderer-ids-unique", ["ids", "uniqueCount"]],
  ["space-selection", "space-text-preserved", ["text", "expectedText"]],
  [
    "space-selection",
    "nested-controls-do-not-select",
    ["linkActivated", "inputFocused", "selectedBefore", "selectedAfter"],
  ],
  [
    "space-selection",
    "selection-handle-independent",
    ["handleFocused", "ariaPressed", "selectedBlockId", "defaultPrevented"],
  ],
  [
    "dirty-guards",
    "builder-cancel-byte-identical",
    ["draftBefore", "draftAfter", "urlBefore", "urlAfter"],
  ],
  [
    "dirty-guards",
    "builder-confirm-navigates-once",
    ["urlBefore", "urlAfter", "navigationCount", "draftDiscarded"],
  ],
  [
    "dirty-guards",
    "entry-cancel-byte-identical",
    ["contentBefore", "contentAfter", "presentationBefore", "presentationAfter"],
  ],
  ["dirty-guards", "entry-cancel-url-stable", ["urlBefore", "urlAfter"]],
  ["dirty-guards", "entry-confirm-navigates-once", ["urlBefore", "urlAfter", "navigationCount"]],
  [
    "dirty-guards",
    "entry-error-retains-both-drafts",
    ["errorVisible", "contentValue", "presentationValue", "contentDirty", "presentationDirty"],
  ],
  ["dirty-guards", "beforeunload-active", ["defaultPrevented", "returnValueSet"]],
  [
    "dirty-guards",
    "successful-retry-clears-persisted-channel",
    [
      "persistedContentMatches",
      "persistedPresentationUnchanged",
      "localPresentationPreserved",
      "contentDirty",
      "presentationDirty",
    ],
  ],
  [
    "related-retry-cache",
    "related-error-visible-before-retry",
    [
      "rootId",
      "errorVisible",
      "retryVisible",
      "rowCount",
      "skeletonChipCount",
      "skeletonRects",
      "emptyVisible",
    ],
  ],
  [
    "related-retry-cache",
    "visible-retry-succeeds",
    [
      "rootId",
      "errorVisible",
      "retryVisible",
      "failureRowIds",
      "failureRowRects",
      "skeletonVisible",
      "emptyVisible",
    ],
  ],
  [
    "related-retry-cache",
    "same-target-visible-rows-retained",
    [
      "rootId",
      "rowIdsBefore",
      "rowIdsPending",
      "rowTextBefore",
      "rowTextPending",
      "rectsBefore",
      "rectsPending",
      "errorVisible",
      "skeletonVisible",
      "emptyVisible",
    ],
  ],
  [
    "related-retry-cache",
    "target-switch-immediate-empty",
    [
      "aRootId",
      "bRootId",
      "aRowCount",
      "bRowCount",
      "aEmptyVisible",
      "bEmptyVisible",
      "aSkeletonChipCount",
      "bSkeletonChipCount",
      "skeletonRects",
    ],
  ],
  [
    "related-retry-cache",
    "stale-a-cannot-commit",
    ["aRootId", "bRootId", "aRowCount", "bRowIds", "staleATextPresent"],
  ],
  [
    "related-retry-cache",
    "only-b-rows-visible",
    [
      "rootId",
      "visibleRowIds",
      "visibleRects",
      "skeletonVisible",
      "emptyVisible",
      "bListGetCountBaseline",
      "bListGetCount",
      "bListGetDelta",
    ],
  ],
  [
    "related-retry-cache",
    "unrelated-draft-byte-identical",
    ["contentBefore", "contentAfter", "presentationBefore", "presentationAfter"],
  ],
  [
    "related-retry-cache",
    "relation-diff-exact",
    ["relationABefore", "relationAAfter", "relationBBefore", "relationBAfter", "otherDiffPaths"],
  ],
  [
    "related-retry-cache",
    "flow6-exit-discarded-once",
    [
      "url",
      "navigationCountBaseline",
      "navigationCountCurrent",
      "navigationCountDelta",
      "entryDirtyBadgeCount",
      "presentationDirtyBadgeCount",
    ],
  ],
  ["responsive-users", "narrow-padding-and-positive-geometry", ["samples"]],
  ["responsive-users", "wide-padding-delta-300", ["samples"]],
  ["responsive-users", "panel-inside-viewport", ["samples"]],
  [
    "responsive-users",
    "user-a-b-a-isolated",
    ["userAFirst", "userB", "userAReturn", "durableA", "metadataEffects", "userAReturnComputed"],
  ],
  [
    "responsive-users",
    "same-user-retained-view-pending",
    ["visibleValue", "durableA", "readPending", "metadataEffect"],
  ],
  [
    "responsive-users",
    "same-user-authoritative-refresh",
    ["before", "server", "after", "metadataEffect"],
  ],
  [
    "responsive-users",
    "newer-local-write-pending",
    ["visibleValue", "newLocalValue", "readPending", "metadataEffect"],
  ],
  [
    "responsive-users",
    "newer-local-write-wins-refresh",
    ["visibleValue", "persistedValue", "staleReadValue", "metadataEffect"],
  ],
  ["responsive-users", "legacy-local-storage-absent", ["key", "value", "writeCount"]],
  ["responsive-users", "light-and-dark-computed", ["userA", "userB"]],
  [
    "responsive-users",
    "second-a-intent-visible-before-exit",
    ["visibleValue", "queuedIntent", "firstWritePending", "metadataEffect"],
  ],
  ["responsive-users", "user-b-default-before-release", ["response", "metadataEffect"]],
  ["responsive-users", "user-b-default-unchanged", ["before", "after", "metadataEffect"]],
  [
    "responsive-users",
    "final-a-retry-converges",
    ["visibleValue", "persistedValue", "writePending", "unhandledRejectionCount", "metadataEffect"],
  ],
]);

export const THEME_STATE_TRANSITIONS = deepFreezeExact([
  { actionId: "tc-004-dark-toggle", proofActionId: "tc-005-dark-proof", from: "light", to: "dark" },
  {
    actionId: "tk-001-light-toggle",
    proofActionId: "tk-002-light-proof",
    from: "dark",
    to: "light",
  },
  { actionId: "ss-008-dark-toggle", proofActionId: "ss-009-dark-proof", from: "light", to: "dark" },
  {
    actionId: "dg-004-light-toggle",
    proofActionId: "dg-005-light-proof",
    from: "dark",
    to: "light",
  },
  { actionId: "dg-040-dark-toggle", proofActionId: "dg-041-dark-proof", from: "light", to: "dark" },
  {
    actionId: "ru-036-light-toggle",
    proofActionId: "ru-037-light-proof",
    from: "dark",
    to: "light",
  },
  {
    actionId: "ru-071-b-dark-toggle",
    proofActionId: "ru-072-b-dark-capture",
    from: "light",
    to: "dark",
  },
  {
    actionId: "ru-081-a2-light-toggle",
    proofActionId: "ru-082-isolation-proof",
    from: "dark",
    to: "light",
  },
]);

export const PAGE_STATE_TRANSITIONS = deepFreezeExact([
  { actionId: "set-005-open", from: "closed", to: "p1-selected" },
  { actionId: "rc-019-related-tab-new", from: "p1-selected", to: "p2-selected" },
  { actionId: "rc-022-related-tab-origin", from: "p2-selected", to: "p1-selected-with-p2" },
  { actionId: "rc-044-close-second-tab", from: "p1-selected-with-p2", to: "p1-selected" },
  { actionId: "rc-045-origin-proof", from: "p1-selected", to: "p1-selected" },
  { actionId: "end-006-close", from: "p1-selected", to: "closed" },
]);

export const AUTH_STATE_TRANSITIONS = deepFreezeExact([
  { actionId: "set-011a-bootstrap-auth-settled", from: "anonymous", to: "bootstrap" },
  { actionId: "ru-040a-bootstrap-signout-settled", from: "bootstrap", to: "anonymous" },
  { actionId: "ru-043a-a-identity-settled", from: "anonymous", to: "user-a" },
  { actionId: "ru-066a-a-signout-settled", from: "user-a", to: "anonymous" },
  { actionId: "ru-069a-b-identity-settled", from: "anonymous", to: "user-b" },
  { actionId: "ru-076a-b-signout-settled", from: "user-b", to: "anonymous" },
  { actionId: "ru-079a-a2-identity-settled", from: "anonymous", to: "user-a" },
  { actionId: "ru-090a-a-exit-signout-settled", from: "user-a", to: "anonymous" },
  { actionId: "ru-093a-b2-identity-settled", from: "anonymous", to: "user-b" },
  { actionId: "ru-102a-b2-signout-settled", from: "user-b", to: "anonymous" },
  { actionId: "ru-105a-a3-identity-settled", from: "anonymous", to: "user-a" },
]);

export const ROUTE_STATE_MACHINES = deepFreezeExact({
  "media-prior-resolution": {
    mode: "delayed",
    method: "GET",
    operations: ["route-setup", "route-hit-read", "route-release", "unroute"],
    states: ["absent", "installed", "hit", "released", "absent"],
  },
  "entry-save-failure": {
    mode: "malformed",
    method: "PATCH",
    operations: ["route-setup", "route-hit-read", "unroute"],
    states: ["absent", "installed", "hit", "absent"],
  },
  "related-first-failure": {
    mode: "malformed",
    method: "GET",
    operations: ["route-setup", "route-hit-read", "unroute"],
    states: ["absent", "installed", "hit", "absent"],
  },
  "related-a-refresh": {
    mode: "delayed",
    method: "GET",
    operations: ["route-setup", "route-hit-read", "route-release", "unroute"],
    states: ["absent", "installed", "hit", "released", "absent"],
  },
  "preference-a-read-refresh": {
    mode: "delayed-preference-read",
    method: "GET",
    operations: ["route-setup", "route-hit-read", "route-release", "unroute"],
    states: ["absent", "installed", "hit", "released", "absent"],
  },
  "preference-a-write-exit": {
    mode: "abort-aware-preference-write",
    method: "PATCH",
    operations: ["route-setup", "route-hit-read", "route-release", "unroute"],
    states: ["absent", "installed", "hit", "released", "absent"],
  },
});

export const BROWSER_BUILDER_KINDS = Object.freeze([
  "open",
  "logger-install",
  "goto",
  "resize",
  "fill",
  "click",
  "observe",
  "blocksBefore",
  "captureNew",
  "assert",
  "route",
  "screen",
  "media-count-before-release",
  "media-count-after-release",
  "logs",
  "focus",
  "press",
  "type",
  "dispatchAndCaptureSelectionHandle",
  "tab-new",
  "tab-select",
  "tab-close",
  "authRateWindowBarrier",
  "cleanup-release-unroute",
  "cleanup-route-list",
  "cleanup-console-errors",
  "cleanup-console-warnings",
  "cleanup-page-errors",
  "cleanup-close",
  "cleanup-session-absence",
]);

export const RUNTIME_BUILDER_KINDS = Object.freeze([
  "storage",
  "host",
  "health",
  "apiPublicRead",
  "settingsRead",
  "isolatedApiSessionLogin",
  "isolatedApiSessionCsrfCapture",
  "fixture",
  "fixtureRead",
  "api",
  "apiRead",
  "isolatedApiSessionApiReadAs",
  "isolatedApiSessionApiAs",
]);

export const OBSERVATION_OUTPUT_FIELDS = deepFreezeExact({
  "bootstrap-auth-identity-settled": ["url", "userMenuVisible", "userName"],
  "theme-light": ["theme", "rootColor", "bodyColor", "toggleAriaPressed"],
  "binding-after-save": ["screenId", "bindings"],
  "safe-link-anchor-before-activation": ["tagName", "href", "rect"],
  "theme-dark": ["theme", "rootColor", "bodyColor", "toggleAriaPressed"],
  "outer-tabs-details-state": [
    "activeTabId",
    "visiblePanelIds",
    "hiddenPanelIds",
    "armedSlotId",
    "rects",
  ],
  "outer-tabs-history-state": [
    "activeTabId",
    "visiblePanelIds",
    "hiddenPanelIds",
    "armedSlotId",
    "rects",
  ],
  "preview-shell-desktop": ["shellVisible", "device", "outerTabsVisible", "innerTabsVisible"],
  "key-step-arrow-left": ["key", "focusedTabText", "focusedTabId", "selectedTabId", "tabIndex"],
  "key-step-arrow-right": ["key", "focusedTabText", "focusedTabId", "selectedTabId", "tabIndex"],
  "key-step-home": ["key", "focusedTabText", "focusedTabId", "selectedTabId", "tabIndex"],
  "key-step-end": ["key", "focusedTabText", "focusedTabId", "selectedTabId", "tabIndex"],
  "selected-block-before-nested-controls": ["selectedBlockId", "url"],
  "selected-block-after-nested-input": ["selectedBlockId", "focused", "url"],
  "selected-block-after-nested-link": ["selectedBlockId", "focused", "url"],
  "builder-draft-url-before-cancel": ["draftBytes", "url", "navigationCount"],
  "entry-drafts-url-before-cancel": ["contentBytes", "presentationBytes", "url", "navigationCount"],
  "entry-save-failure-ui-settled": ["errorVisible", "saveEnabled", "saveLabel"],
  "relation-pickers-a-b-warm": ["aButtons", "bButtons", "aRows", "bListGetCount"],
  "related-unrelated-drafts-before": ["contentBytes", "presentationBytes"],
  "related-a-visible-baseline": [
    "rootId",
    "rowIds",
    "rowText",
    "rects",
    "skeletonCount",
    "emptyVisible",
    "navigationCount",
  ],
  "related-tab-save-settled": [
    "method",
    "pathname",
    "status",
    "entryId",
    "title",
    "saveEnabled",
    "savingAbsent",
  ],
  "geometry-320-closed": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-320-open": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-390-closed": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-390-open": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-480-closed": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-480-open": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-1024-closed": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-1024-open": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-1280-closed": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "geometry-1280-open": [
    "width",
    "state",
    "viewportWidth",
    "paddingRight",
    "scrollerBorder",
    "scrollerContent",
    "panel",
  ],
  "theme-light-user-a-candidate": ["theme", "rootColor", "bodyColor", "toggleAriaPressed"],
  "signout-settled-bootstrap": [
    "url",
    "loginEmailVisible",
    "loginPasswordVisible",
    "loginSubmitVisible",
  ],
  "auth-identity-settled-users-a": ["url", "userMenuVisible", "userName"],
  "user-a-light-computed": ["theme", "rootColor", "bodyColor", "toggleAriaPressed"],
  "preference-a-write-settled": [
    "sequence",
    "method",
    "pathname",
    "status",
    "userIdMatches",
    "value",
    "switchChecked",
    "switchRect",
    "metadataRect",
  ],
  "nondefault-browser-patch-settled": [
    "sequence",
    "method",
    "pathname",
    "status",
    "userIdMatches",
    "value",
  ],
  "new-local-browser-patch-settled": [
    "sequence",
    "method",
    "pathname",
    "status",
    "userIdMatches",
    "value",
  ],
  "signout-settled-user-a": [
    "url",
    "loginEmailVisible",
    "loginPasswordVisible",
    "loginSubmitVisible",
  ],
  "auth-identity-settled-users-b": ["url", "userMenuVisible", "userName"],
  "user-b-dark-computed": [
    "theme",
    "rootColor",
    "bodyColor",
    "toggleAriaPressed",
    "metadataEffect",
  ],
  "signout-settled-user-b": [
    "url",
    "loginEmailVisible",
    "loginPasswordVisible",
    "loginSubmitVisible",
  ],
  "signout-settled-user-a-with-abort": [
    "url",
    "loginEmailVisible",
    "loginPasswordVisible",
    "loginSubmitVisible",
    "clientDiscarded",
  ],
  "post-redirect-a-fresh-read-settled": [
    "sequence",
    "method",
    "pathname",
    "status",
    "activeUserMenuVisible",
    "value",
    "switchChecked",
    "metadataRect",
  ],
});

export const REQUIRED_SCREENSHOT_PATHS = Object.freeze([
  "_docs/_workflows/_smoke/task-540-wf540smoke-button-image-light.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-media-prior-pending.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-tabs-content-dark.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-tabs-keyboard-light.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-space-selection-dark.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-dirty-save-failure.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-dirty-guards-final.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-related-first-failure.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-related-a-stale.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-related-b-dark.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-a-light.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-b-dark.png",
  "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-a-converged.png",
]);

export const SCREENSHOT_DESCRIPTOR_BY_ACTION_ID = deepFreezeExact({
  "bi-028-media-pending-shot": {
    screenshotId: "screenshot/bi-028-media-pending-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-media-prior-pending.png",
  },
  "bi-067-final-shot": {
    screenshotId: "screenshot/bi-067-final-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-button-image-light.png",
  },
  "tc-042-shot": {
    screenshotId: "screenshot/tc-042-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-tabs-content-dark.png",
  },
  "tk-028-shot": {
    screenshotId: "screenshot/tk-028-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-tabs-keyboard-light.png",
  },
  "ss-029-shot": {
    screenshotId: "screenshot/ss-029-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-space-selection-dark.png",
  },
  "dg-033-failure-shot": {
    screenshotId: "screenshot/dg-033-failure-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-dirty-save-failure.png",
  },
  "dg-042-final-shot": {
    screenshotId: "screenshot/dg-042-final-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-dirty-guards-final.png",
  },
  "rc-009-failure-shot": {
    screenshotId: "screenshot/rc-009-failure-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-related-first-failure.png",
  },
  "rc-033-stale-shot": {
    screenshotId: "screenshot/rc-033-stale-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-related-a-stale.png",
  },
  "rc-037-final-shot": {
    screenshotId: "screenshot/rc-037-final-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-related-b-dark.png",
  },
  "ru-048-a-first-shot": {
    screenshotId: "screenshot/ru-048-a-first-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-a-light.png",
  },
  "ru-074-b-shot": {
    screenshotId: "screenshot/ru-074-b-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-b-dark.png",
  },
  "ru-109-converged-shot": {
    screenshotId: "screenshot/ru-109-converged-shot",
    path: "_docs/_workflows/_smoke/task-540-wf540smoke-responsive-user-a-converged.png",
  },
});

export const EXECUTABLE_REGISTRY_KEY_SHA256 = deepFreezeExact({
  runtimeOperations: "29040b4ce9625fe454bfea8f2d68c169800cdf2fcbb3e15761f151254f9ac447",
  browserRunCodeSources: "62f56b099d2dfcec21d68479fedc55b728525df7f022a0bbe7520647d1ba3e3f",
});

export const SCENARIO_BY_PREFIX = Object.freeze({
  set: "setup",
  bi: "button-image",
  tc: "tabs-content",
  tk: "tabs-keyboard-aria",
  ss: "space-selection",
  dg: "dirty-guards",
  rc: "related-retry-cache",
  ru: "responsive-users",
  end: "cleanup",
});

export const PAGE_IDENTITY = Object.freeze({
  runtime: Object.freeze({ pageId: null, tabIndex: null }),
  global: Object.freeze({ pageId: null, tabIndex: null }),
  "p1/0": Object.freeze({ pageId: "wf540-page-1", tabIndex: 0 }),
  "p2/1": Object.freeze({ pageId: "wf540-page-2", tabIndex: 1 }),
});

export const FIXTURE_CAPTURE_BY_ACTION = Object.freeze({
  "set-012-user-a-create": ["user-a.id"],
  "set-014-user-b-create": ["user-b.id"],
  "set-016-editable-type-create": ["content-type-editable.id"],
  "set-018-related-a-type-create": ["content-type-related-a.id"],
  "set-020-related-b-type-create": ["content-type-related-b.id"],
  "set-021a-related-failure-type-create": ["content-type-related-failure.id"],
  "set-022-related-a1-create": ["related-entry-a1.id"],
  "set-024-related-a2-create": ["related-entry-a2.id"],
  "set-026-related-b1-create": ["related-entry-b1.id"],
  "set-028-related-b2-create": ["related-entry-b2.id"],
  "set-029a-related-failure1-create": ["related-entry-failure1.id"],
  "set-030-media-upload": ["media.id", "media.resolved-url", "media.storage-key"],
  "set-033-entry-create": ["entry.id"],
  "set-035-screen-create": ["screen.id"],
  "set-037-retry-screen-create": ["retry-screen.id"],
});

export const FIXTURE_SUBJECT_CAPTURE = Object.freeze({
  "user-a": "user-a.id",
  "user-b": "user-b.id",
  "content-type-editable": "content-type-editable.id",
  "content-type-related-a": "content-type-related-a.id",
  "content-type-related-b": "content-type-related-b.id",
  "content-type-related-failure": "content-type-related-failure.id",
  "related-entry-a1": "related-entry-a1.id",
  "related-entry-a2": "related-entry-a2.id",
  "related-entry-b1": "related-entry-b1.id",
  "related-entry-b2": "related-entry-b2.id",
  "related-entry-failure1": "related-entry-failure1.id",
  media: "media.id",
  "editable-entry": "entry.id",
  screen: "screen.id",
  "retry-screen": "retry-screen.id",
});

export const RUNTIME_CAPTURE_BY_ACTION = Object.freeze({
  "bi-005-button-capture": ["palette.button"],
  "bi-047-image-capture": ["palette.image"],
  "bi-052-field-capture": ["palette.media-field"],
  "tc-009-tabs-capture": ["palette.outer-tabs"],
  "tc-017-text-one-capture": ["palette.tab-one-text"],
  "tc-023-text-two-capture": ["palette.tab-two-text"],
  "tc-029-text-three-capture": ["palette.tab-three-text"],
  "tk-008-inner-capture": ["palette.inner-tabs"],
  "dg-009-dirty-capture": ["palette.dirty-text"],
});

export const RUNTIME_CAPTURE_EXPRESSIONS = Object.freeze({
  "palette.button": "palette.button",
  "palette.image": "palette.image",
  "palette.mediaField": "palette.media-field",
  "palette.outerTabs": "palette.outer-tabs",
  "palette.tabOneText": "palette.tab-one-text",
  "palette.tabTwoText": "palette.tab-two-text",
  "palette.tabThreeText": "palette.tab-three-text",
  "palette.innerTabs": "palette.inner-tabs",
  "palette.dirtyText": "palette.dirty-text",
});

export const CAPTURE_INPUTS_BY_EXPRESSION = Object.freeze({
  "paths.builder": ["screen.id"],
  "paths.records": ["screen.id"],
  "paths.entry": ["screen.id", "entry.id"],
  "paths.retryEntry": ["retry-screen.id", "entry.id"],
  "paths.relatedEntryA1Editor": ["related-entry-a1.id"],
  "users.a.id": ["user-a.id"],
  "users.b.id": ["user-b.id"],
  "screen.id": ["screen.id"],
  "retryScreen.id": ["retry-screen.id"],
  "entry.id": ["entry.id"],
  "media.id": ["media.id"],
  "media.resolvedUrl": ["media.resolved-url"],
  "media.storageKey": ["media.storage-key"],
  "relatedEntries.a1.id": ["related-entry-a1.id"],
  "relatedEntries.a2.id": ["related-entry-a2.id"],
  "relatedEntries.b1.id": ["related-entry-b1.id"],
  "relatedEntries.b2.id": ["related-entry-b2.id"],
  "relatedEntries.failure1.id": ["related-entry-failure1.id"],
});
